<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Lookup: upload addresses → ACD codes – acd: Vienna ACD</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-6366b8537f22fe2521dbe9c1a8a1a9f2.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">acd: Vienna ACD</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../vignettes/articles/dashboard.html"> 
<span class="menu-text">Dashboard</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../vignettes/articles/methodology.html"> 
<span class="menu-text">Methodology</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../vignettes/articles/lookup.html"> 
<span class="menu-text">Lookup</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="../../vignettes/articles/upload.html" aria-current="page"> 
<span class="menu-text">Upload → ACD</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../vignettes/articles/scrollytell_de.html"> 
<span class="menu-text">DE: Wie die Daten funktionieren</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content column-page" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Lookup: upload addresses → ACD codes</h1>
<p class="subtitle lead">Bulk address resolution against Vienna’s ADRESSENOGD</p>
</div>



<div class="quarto-title-meta column-page">

    
  
    
  </div>
  


</header>


<!-- ── Upload page styles (toolbar + bilingual + dark mode) ──────────────── -->
<style>
/* ── Base typography ─────────────────────────────────────────────────────── */
main, .quarto-container, .upload-page-prose,
.upload-page-prose p, .upload-page-prose li,
.upload-page-prose td, .upload-page-prose th {
  font-size: var(--upload-font-size, 1.15em);
}
:root { --upload-font-size: 1.15em; }

.upload-page-prose table { width: 100%; border-collapse: collapse; }
.upload-page-prose table th, .upload-page-prose table td {
  padding: 6px 10px; border-bottom: 1px solid #dee2e6;
  vertical-align: top;
}
.upload-page-prose table th.step-col,
.upload-page-prose table td.step-col {
  width: 4.5em;
  text-align: center;
  white-space: nowrap;
}

/* ── Toolbar ─────────────────────────────────────────────────────────────── */
.upload-toolbar {
  position: sticky; top: 0; z-index: 10;
  display: flex; gap: 8px; align-items: center; justify-content: flex-end;
  padding: 6px 12px;
  background: var(--bg, #fff);
  border-bottom: 1px solid var(--border, #dee2e6);
  flex-wrap: nowrap;
}
@media (max-width: 600px) { .upload-toolbar { flex-wrap: wrap; } }
.upload-toolbar button {
  padding: 4px 10px; border-radius: 4px; border: 1px solid var(--border, #ced4da);
  background: var(--card-bg, #f8f9fa); color: var(--text, #212529);
  cursor: pointer; font-size: 0.88em; font-weight: 600; white-space: nowrap;
}
.upload-toolbar button:hover { opacity: 0.8; }
.upload-toolbar .toolbar-sep {
  color: var(--border, #ced4da); font-size: 0.8em; user-select: none;
}

/* ── Bilingual visibility ────────────────────────────────────────────────── */
body[lang="en"] [data-lang="de"] { display: none; }
body[lang="de"] [data-lang="en"] { display: none; }

/* ── Dark mode ───────────────────────────────────────────────────────────── */
body.dark-mode {
  --bg: #1a1a2e;
  --text: #e0e0e0;
  --card-bg: #16213e;
  --border: #2a2a4a;
  --link: #4ea8de;
}
body.dark-mode main,
body.dark-mode .upload-page-prose {
  background: var(--bg); color: var(--text);
}
body.dark-mode #drop-zone {
  background: var(--card-bg); border-color: var(--border); color: var(--text);
}
body.dark-mode #sample-strip {
  background: #2a2a3e; border-color: #4a4a5a; color: #f0e8c0;
}
body.dark-mode .upload-page-prose table th,
body.dark-mode .upload-page-prose table td {
  border-color: var(--border);
}
body.dark-mode a { color: var(--link); }
body.dark-mode .upload-toolbar {
  background: var(--card-bg); border-color: var(--border);
}
body.dark-mode #upload-section label,
body.dark-mode #upload-section h4,
body.dark-mode #col-map-section { color: var(--text); }
body.dark-mode #match-summary {
  background: var(--card-bg); border-color: var(--border); color: var(--text);
}
body.dark-mode #results-section h3,
body.dark-mode #results-section h4 { color: var(--text); }
body.dark-mode #empty-state-msg { color: #aaa; }
body.dark-mode select {
  background: var(--card-bg); color: var(--text); border-color: var(--border);
}
body.dark-mode #progress-bar { background: #4ea8de; }
body.dark-mode #progress-msg { color: #ccc; }
/* Drop zone hover in dark mode */
body.dark-mode #drop-zone:hover,
body.dark-mode #drop-zone.drag-over { background: #1e2a3e !important; }
body.dark-mode p#file-name-display { color: #fff; }
body.dark-mode #match-summary span[style*="198754"] { color: #69d4a0 !important; }
body.dark-mode #match-summary span[style*="dc3545"] { color: #f08080 !important; }

/* ── Chart section & caption ─────────────────────────────────────────────── */
#chart-section {
  background: #1a1a1a;
  border-radius: 6px;
  padding: 10px 12px;
}
#district-chart-caption {
  color: #e0e0e0;   /* white-on-dark: contrast ratio >> 4.5:1 vs #1a1a1a */
  font-size: 0.82em;
  line-height: 1.5;
  text-align: left;
  margin-bottom: 6px;
}
#district-chart-caption a { color: #5dadff; }
</style>

<!-- ── Toolbar ─────────────────────────────────────────────────────────────── -->
<div class="upload-toolbar" id="upload-toolbar" role="toolbar" aria-label="Page controls">
  <button id="lang-btn" title="Switch language / Sprache wechseln" aria-label="Switch language">🌐 DE</button>
  <span class="toolbar-sep">|</span>
  <button id="font-up-btn" title="Increase font size" aria-label="Increase font size">A+</button>
  <button id="font-down-btn" title="Decrease font size" aria-label="Decrease font size">A−</button>
  <span class="toolbar-sep">|</span>
  <button id="dark-btn" title="Toggle dark mode" aria-label="Toggle dark mode">🌙</button>
</div>

<!-- ── Toolbar JS ──────────────────────────────────────────────────────────── -->
<script>
(function() {
  // ── Constants ──────────────────────────────────────────────────────────────
  const LS_LANG      = "acd-upload-lang";
  const LS_FONT      = "acd-upload-font-size";
  const LS_DARK      = "acd-upload-dark-mode";
  const FONT_MIN     = 12;
  const FONT_MAX     = 22;
  const FONT_STEP    = 1;
  const FONT_DEFAULT = 17;  // 1.15em equivalent at base 16px → ~18.4; use 17 as round default

  // ── Helpers ────────────────────────────────────────────────────────────────
  function applyLang(lang) {
    document.body.setAttribute("lang", lang);
    const btn = document.getElementById("lang-btn");
    if (btn) {
      btn.textContent = lang === "de" ? "🌐 EN" : "🌐 DE";
      btn.setAttribute("aria-label",
        lang === "de" ? "Switch to English" : "Auf Deutsch wechseln");
      btn.setAttribute("title",
        lang === "de" ? "Switch to English" : "Auf Deutsch wechseln");
    }
    // Swap data-en / data-de textContent on interactive elements (buttons, th, labels)
    document.querySelectorAll("[data-en][data-de]").forEach(el => {
      el.textContent = el.getAttribute("data-" + lang);
    });
  }

  function applyFont(px) {
    document.documentElement.style.setProperty("--upload-font-size", px + "px");
  }

  function applyDark(on) {
    document.body.classList.toggle("dark-mode", on);
    const btn = document.getElementById("dark-btn");
    if (btn) btn.textContent = on ? "☀️" : "🌙";
  }

  // ── First-visit defaults ───────────────────────────────────────────────────
  function detectLang() {
    const saved = localStorage.getItem(LS_LANG);
    if (saved) return saved;
    return (navigator.language || "").startsWith("de") ? "de" : "en";
  }

  function detectDark() {
    const saved = localStorage.getItem(LS_DARK);
    if (saved !== null) return saved === "1";
    return window.matchMedia &&
           window.matchMedia("(prefers-color-scheme: dark)").matches;
  }

  function detectFont() {
    const saved = parseInt(localStorage.getItem(LS_FONT), 10);
    return (saved >= FONT_MIN && saved <= FONT_MAX) ? saved : FONT_DEFAULT;
  }

  // ── Init ───────────────────────────────────────────────────────────────────
  let currentLang = detectLang();
  let currentFont = detectFont();
  let currentDark = detectDark();

  applyLang(currentLang);
  applyFont(currentFont);
  applyDark(currentDark);

  // ── Button wiring (defer until DOM ready) ─────────────────────────────────
  document.addEventListener("DOMContentLoaded", function() {
    applyLang(currentLang);
    applyFont(currentFont);
    applyDark(currentDark);

    document.getElementById("lang-btn").addEventListener("click", function() {
      currentLang = currentLang === "en" ? "de" : "en";
      localStorage.setItem(LS_LANG, currentLang);
      applyLang(currentLang);
    });

    document.getElementById("font-up-btn").addEventListener("click", function() {
      currentFont = Math.min(FONT_MAX, currentFont + FONT_STEP);
      localStorage.setItem(LS_FONT, currentFont);
      applyFont(currentFont);
    });

    document.getElementById("font-down-btn").addEventListener("click", function() {
      currentFont = Math.max(FONT_MIN, currentFont - FONT_STEP);
      localStorage.setItem(LS_FONT, currentFont);
      applyFont(currentFont);
    });

    document.getElementById("dark-btn").addEventListener("click", function() {
      currentDark = !currentDark;
      localStorage.setItem(LS_DARK, currentDark ? "1" : "0");
      applyDark(currentDark);
    });
  });
})();
</script>
<section id="quick-guide" class="level2 upload-page-prose">
<h2 class="anchored" data-anchor-id="quick-guide">Quick guide</h2>
<div data-lang="en">
<p>Upload an Excel (<code>.xlsx</code>) or CSV file with <strong>at least three columns</strong>: postcode (<code>PLZ</code>), street name, and house number. The lookup runs entirely in your browser using <a href="https://duckdb.org/docs/api/wasm/overview.html">DuckDB-Wasm</a> — your file never leaves your device.</p>
</div>
<div data-lang="de">
<p>Laden Sie eine Excel- (<code>.xlsx</code>-) oder CSV-Datei mit <strong>mindestens drei Spalten</strong> hoch: Postleitzahl (<code>PLZ</code>), Straßenname und Hausnummer. Die Suche läuft vollständig in Ihrem Browser via <a href="https://duckdb.org/docs/api/wasm/overview.html">DuckDB-Wasm</a> — Ihre Datei verlässt Ihr Gerät nicht.</p>
</div>
<table class="caption-top table">
<thead>
<tr class="header">
<th class="step-col" data-quarto-table-cell-role="th" data-en="Step" data-de="Schritt">Step</th>
<th data-quarto-table-cell-role="th" data-en="What to do" data-de="Was zu tun ist">What to do</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td class="step-col">1</td>
<td><span data-lang="en">Click <strong>Choose file</strong> (or drag-and-drop)</span> <span data-lang="de">Auf <strong>Datei auswählen</strong> klicken (oder per Drag &amp; Drop)</span></td>
</tr>
<tr class="even">
<td class="step-col">2</td>
<td><span data-lang="en">Map your columns to PLZ / Street / HouseNumber if the auto-detect is wrong</span> <span data-lang="de">Spalten PLZ / Straße / Hausnummer zuordnen, falls die Erkennung fehlschlägt</span></td>
</tr>
<tr class="odd">
<td class="step-col">3</td>
<td><span data-lang="en">Click <strong>Run lookup</strong></span> <span data-lang="de">Auf <strong>Suche starten</strong> klicken</span></td>
</tr>
<tr class="even">
<td class="step-col">4</td>
<td><span data-lang="en">Review results and click <strong>Download CSV</strong></span> <span data-lang="de">Ergebnisse prüfen und auf <strong>CSV herunterladen</strong> klicken</span></td>
</tr>
</tbody>
</table>
<div data-lang="en">
<p><strong>Example values:</strong> postcode <code>1210</code>, street <code>Achengasse</code>, house number <code>3</code> → ACD code <code>070268</code>, SCD <code>00012</code>.</p>
<p><strong>Coverage:</strong> 291,823 registered address points, 196,142 unique ACD codes. Source: <a href="https://www.data.gv.at/katalog/dataset/stadt-wien_adressenwien">Vienna Open Government Data WFS</a> (<a href="https://data.wien.gv.at/daten/geo?service=WFS&amp;request=DescribeFeatureType&amp;typeNames=ogdwien:ADRESSENOGD"><code>ogdwien:ADRESSENOGD</code></a>), snapshot 2026-05-02.</p>
<p><strong>Privacy:</strong> addresses you upload are processed locally in your browser via <a href="https://duckdb.org/docs/api/wasm/overview.html">DuckDB-Wasm</a>. They are never sent to any server.</p>
</div>
<div data-lang="de">
<p><strong>Beispielwerte:</strong> PLZ <code>1210</code>, Straße <code>Achengasse</code>, Hausnummer <code>3</code> → ACD-Code <code>070268</code>, SCD <code>00012</code>.</p>
<p><strong>Abdeckung:</strong> 291.823 registrierte Adresspunkte, 196.142 eindeutige ACD-Codes. Quelle: <a href="https://www.data.gv.at/katalog/dataset/stadt-wien_adressenwien">Wien Open Government Data WFS</a> (<a href="https://data.wien.gv.at/daten/geo?service=WFS&amp;request=DescribeFeatureType&amp;typeNames=ogdwien:ADRESSENOGD"><code>ogdwien:ADRESSENOGD</code></a>), Stand 2026-05-02.</p>
<p><strong>Datenschutz:</strong> Die hochgeladenen Adressen werden lokal in Ihrem Browser verarbeitet via <a href="https://duckdb.org/docs/api/wasm/overview.html">DuckDB-Wasm</a>. Es werden keine Daten an einen Server übertragen.</p>
</div>
</section>
<hr>
<section id="upload-your-file" class="level2">
<h2 class="anchored" data-anchor-id="upload-your-file">Upload your file</h2>
<!-- ── CDN dependencies ─────────────────────────────────────────────────── -->
<script src="https://cdn.jsdelivr.net/npm/papaparse@5.4.1/papaparse.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js"></script>

<!-- ── Upload UI ──────────────────────────────────────────────────────────── -->
<div id="upload-section" style="font-family:sans-serif; max-width:900px;">

  <!-- Sample / template strip -->
  <div id="sample-strip" style="
    margin-bottom:12px; padding:10px 14px;
    background:#fff8dc; border:1px solid #ffe58a; border-radius:6px;
    display:flex; flex-wrap:wrap; gap:10px; align-items:center;
    font-size:0.92em; color:#5a4500;">
    <span style="flex:1; min-width:200px;">
      📄 <strong>
        <span data-lang="en">First time here?</span>
        <span data-lang="de">Zum ersten Mal hier?</span>
      </strong>
      <span data-lang="en">Try a 12-row sample
        (5 matches across Bezirke 21+22, 2 focus-district rows for 20, 2 central, 3 deliberate edge cases).</span>
      <span data-lang="de">Testen Sie mit einer 12-Zeilen-Beispieldatei
        (5 Treffer in den Bezirken 21+22, 2 Fokus-Bezirk-Zeilen für 20, 2 zentral, 3 Grenzfälle).</span>
    </span>
    <button id="try-sample-btn" style="
      padding:6px 14px; background:#0d6efd; color:#fff; border:none;
      border-radius:4px; cursor:pointer; font-weight:600; white-space:nowrap;" data-en="▶ Try with sample" data-de="▶ Beispiel laden">
      ▶ Try with sample
    </button>
    <a id="download-sample-btn" href="../../data/sample_acd_test.xlsx" download="" style="padding:6px 14px; background:#fff; color:#0d6efd;
              border:1px solid #0d6efd; border-radius:4px;
              text-decoration:none; font-weight:600; white-space:nowrap;">
      <span data-lang="en">⬇ Download template</span>
      <span data-lang="de">⬇ Vorlage herunterladen</span>
    </a>
  </div>

  <!-- Drop zone -->
  <div id="drop-zone" style="
    border:2px dashed #6c757d; border-radius:8px; padding:24px 20px;
    text-align:center; background:#f8f9fa; cursor:pointer; margin-bottom:16px;">
    <p style="margin:0; font-size:1.05em; color:#495057;">
      <span data-lang="en">Drag &amp; drop your <strong>.xlsx</strong> or <strong>.csv</strong> file here,
        or <label for="file-input" style="color:#0d6efd; cursor:pointer; text-decoration:underline;">choose file</label>.</span>
      <span data-lang="de">Ziehen Sie Ihre <strong>.xlsx</strong>- oder <strong>.csv</strong>-Datei hierher,
        oder <label for="file-input" style="color:#0d6efd; cursor:pointer; text-decoration:underline;">Datei auswählen</label>.</span>
    </p>
    <input type="file" id="file-input" accept=".xlsx,.csv" style="display:none;">
    <p id="file-name-display" style="margin:8px 0 0; color:#0d6efd; font-size:1.3em; font-weight:bold;"></p>
  </div>

  <!-- Column mapping (hidden until file is loaded) -->
  <div id="col-map-section" style="display:none; margin-bottom:16px;">
    <h4 style="margin-bottom:8px;" class="anchored">
      <span data-lang="en">Column mapping</span>
      <span data-lang="de">Spaltenzuordnung</span>
    </h4>
    <div style="display:flex; flex-wrap:wrap; gap:16px;">
      <label style="display:flex; flex-direction:column; gap:4px; font-size:0.9em;">
        <span data-lang="en">PLZ (postcode)</span>
        <span data-lang="de">PLZ (Postleitzahl)</span>
        <select id="map-plz" style="padding:4px 8px; border-radius:4px; border:1px solid #ced4da;"></select>
      </label>
      <label style="display:flex; flex-direction:column; gap:4px; font-size:0.9em;">
        <span data-lang="en">Street name</span>
        <span data-lang="de">Straßenname</span>
        <select id="map-street" style="padding:4px 8px; border-radius:4px; border:1px solid #ced4da;"></select>
      </label>
      <label style="display:flex; flex-direction:column; gap:4px; font-size:0.9em;">
        <span data-lang="en">House number</span>
        <span data-lang="de">Hausnummer</span>
        <select id="map-hausnr" style="padding:4px 8px; border-radius:4px; border:1px solid #ced4da;"></select>
      </label>
    </div>
  </div>

  <!-- Run lookup button — visible on load (disabled until file is parsed) -->
  <button id="run-btn" disabled="" style="
    margin-top:14px; padding:8px 20px; background:#0d6efd; color:#fff;
    border:none; border-radius:6px; font-size:1em;
    cursor:not-allowed; opacity:0.55;" data-en="Run lookup" data-de="Suche starten">
    Run lookup
  </button>

  <!-- Progress bar -->
  <div id="progress-section" style="display:none; margin-bottom:12px;">
    <p id="progress-msg" style="margin:0 0 6px; font-size:0.9em; color:#495057;"></p>
    <div style="background:#dee2e6; border-radius:4px; height:8px; width:100%;">
      <div id="progress-bar" style="background:#0d6efd; border-radius:4px; height:8px; width:0%; transition:width 0.3s;"></div>
    </div>
  </div>

  <!-- Empty-state message (shown until upload runs) -->
  <p id="empty-state-msg" style="color:#6c757d; font-style:italic; margin-top:8px;">
    <span data-lang="en">Upload a file to begin. No data will leave your browser.</span>
    <span data-lang="de">Datei hochladen, um zu beginnen. Keine Daten verlassen Ihren Browser.</span>
  </p>

</div>

<!-- ── Results section (hidden until lookup runs) ─────────────────────────── -->
<div id="results-section" style="display:none; margin-top:24px; font-family:sans-serif; max-width:1100px;">
  <h3 class="anchored">
    <span data-lang="en">Results</span>
    <span data-lang="de">Ergebnisse</span>
  </h3>

  <!-- Match rate summary -->
  <div id="match-summary" style="
    background:#f8f9fa; border:1px solid #dee2e6; border-radius:6px;
    padding:12px 16px; margin-bottom:16px; font-size:0.92em;">
  </div>

  <!-- Per-district chart -->
  <div id="chart-section" style="margin-bottom:16px;">
    <h4 style="margin-bottom:6px;" class="anchored">
      <span data-lang="en">Match rate by district (PLZ)</span>
      <span data-lang="de">Trefferquote nach Bezirk (PLZ)</span>
    </h4>
    <figcaption id="district-chart-caption" style="font-size:0.82em; color:#e0e0e0; margin-bottom:6px; text-align:left; line-height:1.45;"></figcaption>
    <canvas id="district-chart" height="300" aria-label="Match rate by Vienna district, Cleveland dot plot" style="max-width:700px; width:100%;"></canvas>
    <!-- Accessible data table fallback (screen readers + keyboard users) -->
    <details style="margin-top:6px;">
      <summary style="font-size:0.8em; color:#adb5bd; cursor:pointer;">
        <span data-lang="en">Data table (accessibility)</span>
        <span data-lang="de">Datentabelle (Barrierefreiheit)</span>
      </summary>
      
<table id="district-data-table" class="caption-top" style="font-size:0.78em; border-collapse:collapse; margin-top:4px; color:#e0e0e0;">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="border: 1px solid #555; padding: 3px 8px">District (PLZ)</th>
<th data-quarto-table-cell-role="th" style="border: 1px solid #555; padding: 3px 8px">Total</th>
<th data-quarto-table-cell-role="th" style="border: 1px solid #555; padding: 3px 8px">Matched</th>
<th data-quarto-table-cell-role="th" style="border: 1px solid #555; padding: 3px 8px">Match rate (%)</th>
</tr>
</thead>
<tbody id="district-data-tbody">
</tbody>
</table>

  </details></div>

  <!-- Fix C — REST API fallback button (hidden until unmatched rows exist) -->
  <div id="rest-fallback-section" style="display:none; margin-top:16px;
    padding:12px 16px; background:#fff8dc; border:1px solid #ffe58a;
    border-radius:6px; font-size:0.92em;">
    <p style="margin:0 0 8px;">
      <span data-lang="en">
        <strong>
          <span id="rest-unmatched-count">0</span> rows still unmatched
        </strong> after Fix A + Fix B.
        The city's
        <a href="https://data.wien.gv.at/daten/OGDAddressService.svc/GetAddressInfo" target="_blank" rel="noopener">OGDAddressService REST API</a>
        can attempt server-side fuzzy matching for these rows.
        <em>Unmatched addresses will be sent to data.wien.gv.at.</em>
      </span>
      <span data-lang="de">
        <strong>
          <span id="rest-unmatched-count-de">0</span> Zeilen noch nicht gefunden
        </strong> nach Fix A + Fix B.
        Der städtische
        <a href="https://data.wien.gv.at/daten/OGDAddressService.svc/GetAddressInfo" target="_blank" rel="noopener">OGDAddressService REST-Endpunkt</a>
        kann für diese Zeilen serverseitiges Fuzzy-Matching versuchen.
        <em>Nicht gefundene Adressen werden an data.wien.gv.at übertragen.</em>
      </span>
    </p>
    <div style="display:flex; gap:12px; align-items:center; flex-wrap:wrap;">
      <button id="rest-btn" style="
        padding:7px 18px; background:#fd7e14; color:#fff;
        border:none; border-radius:6px; cursor:pointer; font-size:0.95em; font-weight:600;" data-en="🌐 Try REST API for residual unmatched" data-de="🌐 REST API für verbleibende Adressen versuchen">
        🌐 Try REST API for residual unmatched
      </button>
      <span id="rest-budget-display" style="color:#6c757d; font-size:0.88em;"></span>
    </div>
    <div id="rest-progress-wrap" style="display:none; margin-top:10px;">
      <p id="rest-progress-msg" style="margin:0 0 4px; font-size:0.88em; color:#495057;"></p>
      <div style="background:#dee2e6; border-radius:4px; height:6px; width:100%;">
        <div id="rest-progress-bar" style="background:#fd7e14; border-radius:4px; height:6px; width:0%; transition:width 0.2s;"></div>
      </div>
    </div>
  </div>
</div>
<hr>
</section>
<section id="how-it-works" class="level2 panel-tabset">
<h2 class="panel-tabset anchored" data-anchor-id="how-it-works">How it works</h2>
<section id="algorithm-algorithmus" class="level3">
<h3 class="anchored" data-anchor-id="algorithm-algorithmus">Algorithm / Algorithmus</h3>
<div data-lang="en">
<p>This page does <strong>not</strong> use the project’s spatial join or building-footprint layer. It is a direct address-table lookup against <a href="https://data.wien.gv.at/daten/geo?service=WFS&amp;request=DescribeFeatureType&amp;typeNames=ogdwien:ADRESSENOGD"><code>ogdwien:ADRESSENOGD</code></a> (291,823 registered address points), running in <a href="https://duckdb.org/docs/api/wasm/overview.html">DuckDB-Wasm</a> entirely in your browser. See the <a href="../../vignettes/articles/methodology.html">Methodology page</a> for the dashboard’s spatial pipeline (different layers, different question).</p>
<p>The join uses three normalised keys:</p>
<ul>
<li><strong>PLZ</strong> — four-digit postcode (cast to <code>VARCHAR</code>)</li>
<li><strong>Street name</strong> — <code>LOWER(TRIM(name_str))</code> matched against the user column</li>
<li><strong>House number</strong> — <code>LOWER(TRIM(name_onr))</code> matched against the user column</li>
</ul>
<p>Schrebergärten / garden-plot addresses with a <code>/</code> in the street or <code>Parz</code> in the house-number column are split into two lookup attempts automatically.</p>
<section id="what-this-page-does-not-do" class="level3">
<h3 class="anchored" data-anchor-id="what-this-page-does-not-do">What this page does NOT do</h3>
<ul>
<li>❌ It does not run the <code>R/join_buildings_zones.R</code> spatial join</li>
<li>❌ It does not return <code>confidence_tier</code> (A–E distance-based labels)</li>
<li>❌ It does not return <code>zone_id</code> or <code>nearest_zone_dist_m</code> for matched buildings</li>
<li>❌ It does not consult the <code>GEBAEUDEINFOOGD</code> building-footprint layer</li>
</ul>
<p>Spatial enrichment of matched rows with these fields is tracked as a follow-up in <a href="https://github.com/JohnGavin/acd_area_climate_design/issues/42">issue #42</a>.</p>
<p><strong>Match quality legend:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Value</th>
<th>Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>exact</code></td>
<td>All three keys matched exactly and there is exactly one ACD for this address</td>
</tr>
<tr class="even">
<td><code>ambiguous_multi</code></td>
<td>All three keys matched but <strong>multiple ACDs</strong> exist for this address (multi-unit building). The first ACD is shown; click the ⚠ badge to see all. <code>acd_count</code> = number of ACDs, <code>acd_codes</code> = comma-joined list</td>
</tr>
<tr class="odd">
<td><code>fuzzy_nearest_house</code></td>
<td>PLZ + street matched; nearest existing house number used (distance shown in <code>house_distance</code> column)</td>
</tr>
<tr class="even">
<td><code>split_both</code></td>
<td>Composite <code>A/B</code> street — both halves resolved to an ACD (<code>ACD</code> = first, <code>acd_b</code> = second)</td>
</tr>
<tr class="odd">
<td><code>split_partial</code></td>
<td>Composite <code>A/B</code> street — only one half resolved</td>
</tr>
<tr class="even">
<td><code>rest_api_fallback</code></td>
<td>Fix C: matched via the city’s OGDAddressService REST API; <code>rest_ranking</code> column shows API confidence</td>
</tr>
<tr class="odd">
<td><code>unmatched_after_rest</code></td>
<td>REST API was tried but returned no match</td>
</tr>
<tr class="even">
<td><code>rest_skipped_over_budget</code></td>
<td>REST API skipped — session budget of 250 calls already consumed</td>
</tr>
<tr class="odd">
<td><code>unmatched</code></td>
<td>No row in <a href="https://data.wien.gv.at/daten/geo?service=WFS&amp;request=DescribeFeatureType&amp;typeNames=ogdwien:ADRESSENOGD"><code>ADRESSENOGD</code></a> matched (REST API not yet tried)</td>
</tr>
</tbody>
</table>
<p><em>Note: this DE/EN toggle is complementary to the German narrative vignette at <a href="scrollytell_de.html">scrollytell_de.html</a> — that page tells the story of ACD codes; this page is a utility tool.</em></p>
</section>
</div>
<div data-lang="de">
<p>Diese Seite nutzt <strong>nicht</strong> die räumliche Verknüpfung oder die Gebäudegrundriss-Ebene des Projekts. Es handelt sich um eine direkte Adresstabellen-Suche gegen <a href="https://data.wien.gv.at/daten/geo?service=WFS&amp;request=DescribeFeatureType&amp;typeNames=ogdwien:ADRESSENOGD"><code>ogdwien:ADRESSENOGD</code></a> (291.823 registrierte Adresspunkte), die vollständig in <a href="https://duckdb.org/docs/api/wasm/overview.html">DuckDB-Wasm</a> im Browser läuft. Die räumliche Pipeline des Dashboards ist auf der <a href="../../vignettes/articles/methodology.html">Methodik-Seite</a> beschrieben.</p>
<p>Die Verknüpfung verwendet drei normalisierte Schlüssel:</p>
<ul>
<li><strong>PLZ</strong> — vierstellige Postleitzahl (als <code>VARCHAR</code>)</li>
<li><strong>Straßenname</strong> — <code>LOWER(TRIM(name_str))</code> mit der Benutzerspalte abgeglichen</li>
<li><strong>Hausnummer</strong> — <code>LOWER(TRIM(name_onr))</code> mit der Benutzerspalte abgeglichen</li>
</ul>
<p>Schrebergarten-Adressen mit <code>/</code> im Straßennamen oder <code>Parz</code> in der Hausnummer werden in zwei Suchversuche aufgeteilt (Fix B). Für Zeilen, bei denen die Straße vorhanden ist, aber die exakte Hausnummer fehlt, wird die nächstgelegene vorhandene Hausnummer herangezogen (Fix A).</p>
<section id="was-diese-seite-nicht-leistet" class="level3">
<h3 class="anchored" data-anchor-id="was-diese-seite-nicht-leistet">Was diese Seite nicht leistet</h3>
<ul>
<li>❌ Kein räumlicher Join via <code>R/join_buildings_zones.R</code></li>
<li>❌ Kein <code>confidence_tier</code> (A–E, distanzbasiert)</li>
<li>❌ Kein <code>zone_id</code> oder <code>nearest_zone_dist_m</code></li>
<li>❌ Kein Abgleich mit der <code>GEBAEUDEINFOOGD</code>-Gebäudegrundriss-Ebene</li>
</ul>
<p>Die räumliche Anreicherung wird als Folgeaufgabe in <a href="https://github.com/JohnGavin/acd_area_climate_design/issues/42">Issue #42</a> verfolgt.</p>
<p><strong>Treffer-Qualität Legende:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Wert</th>
<th>Bedeutung</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>exact</code></td>
<td>Alle drei Schlüssel exakt übereinstimmend und genau eine ACD für diese Adresse vorhanden</td>
</tr>
<tr class="even">
<td><code>ambiguous_multi</code></td>
<td>Alle drei Schlüssel stimmen überein, aber <strong>mehrere ACDs</strong> existieren für diese Adresse (Mehrfamilienhaus / Stiegenhäuser). Die erste ACD wird angezeigt; ⚠-Badge anklicken, um alle zu sehen. <code>acd_count</code> = Anzahl ACDs, <code>acd_codes</code> = kommagetrennte Liste</td>
</tr>
<tr class="odd">
<td><code>fuzzy_nearest_house</code></td>
<td>PLZ + Straße stimmen überein; nächstgelegene vorhandene Hausnummer verwendet (Abstand in <code>house_distance</code>)</td>
</tr>
<tr class="even">
<td><code>split_both</code></td>
<td>Zusammengesetzte <code>A/B</code>-Adresse — beide Hälften aufgelöst (<code>ACD</code> = erste, <code>acd_b</code> = zweite)</td>
</tr>
<tr class="odd">
<td><code>split_partial</code></td>
<td>Zusammengesetzte <code>A/B</code>-Adresse — nur eine Hälfte aufgelöst</td>
</tr>
<tr class="even">
<td><code>rest_api_fallback</code></td>
<td>Fix C: Treffer via städtischem OGDAddressService REST-Endpunkt; Spalte <code>rest_ranking</code> zeigt API-Konfidenz</td>
</tr>
<tr class="odd">
<td><code>unmatched_after_rest</code></td>
<td>REST API wurde aufgerufen, aber kein Treffer zurückgegeben</td>
</tr>
<tr class="even">
<td><code>rest_skipped_over_budget</code></td>
<td>REST API übersprungen — Sitzungsbudget von 250 Aufrufen bereits ausgeschöpft</td>
</tr>
<tr class="odd">
<td><code>unmatched</code></td>
<td>Keine Zeile in <a href="https://data.wien.gv.at/daten/geo?service=WFS&amp;request=DescribeFeatureType&amp;typeNames=ogdwien:ADRESSENOGD"><code>ADRESSENOGD</code></a> gefunden (REST API noch nicht versucht)</td>
</tr>
</tbody>
</table>
<p><em>Hinweis: Der DE/EN-Umschalter ergänzt das deutsche Erzählvignette unter <a href="scrollytell_de.html">scrollytell_de.html</a> — jene Seite erklärt ACD-Codes; diese Seite ist ein Werkzeug.</em></p>
</section>
</div>
</section>
<section id="performance" class="level3">
<h3 class="anchored" data-anchor-id="performance">Performance</h3>
<div data-lang="en">
<p><strong>Match rate on the user’s 2,039-row test file (mostly Bezirke 21 + 22):</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 42%">
<col style="width: 34%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th>Algorithm</th>
<th style="text-align: right;">Matched</th>
<th style="text-align: right;">Rate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Baseline — exact join only (pre-#37)</td>
<td style="text-align: right;">1,661</td>
<td style="text-align: right;">81.5%</td>
</tr>
<tr class="even">
<td>Fix A + Fix B (post-#37)</td>
<td style="text-align: right;">1,921</td>
<td style="text-align: right;">94.2%</td>
</tr>
<tr class="odd">
<td><strong>Fix A + Fix B + Fix C REST API (post-#48)</strong></td>
<td style="text-align: right;"><strong>1,976</strong></td>
<td style="text-align: right;"><strong>96.9%</strong></td>
</tr>
</tbody>
</table>
<p>Fix C recovered 55 of the 118 residual unmatched rows (46.6% of residual) in 4 seconds using concurrency 8. The remaining 63 rows have no match in the live Wien address register. See <code>analysis/qa/upload_match_rate_post_c.md</code> for the full diagnostic.</p>
<p>Fix A (fuzzy nearest house) recovers 246 rows (12.1 pp). Fix B (composite split) recovers 14 rows (0.7 pp). The residual 118 unmatched rows are predominantly Schrebergarten parcel addresses and streets absent from ADRESSENOGD.</p>
<p>All timings are for the DuckDB-WASM query phase after warm-up (first visit adds ~3–4 s for DuckDB cold-start; subsequent queries on the same page load are fast). The fuzzy fallback adds one extra query for unmatched rows only — negligible when most rows match on the first pass.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Rows</th>
<th>Operation</th>
<th>Estimated time</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>12 (sample)</td>
<td>One DuckDB join</td>
<td>&lt;100 ms after warm-up</td>
</tr>
<tr class="even">
<td>100</td>
<td>One DuckDB join</td>
<td>&lt;200 ms</td>
</tr>
<tr class="odd">
<td>500</td>
<td>One DuckDB join</td>
<td>&lt;300 ms</td>
</tr>
<tr class="even">
<td>2,000</td>
<td>Two DuckDB joins (exact + fuzzy pass)</td>
<td>~600 ms</td>
</tr>
<tr class="odd">
<td>10,000</td>
<td>Two DuckDB joins + chunked CSV write</td>
<td>1.5–2.5 s</td>
</tr>
</tbody>
</table>
</div>
<div data-lang="de">
<p><strong>Trefferquote auf der 2.039-zeiligen Testdatei der Nutzerin (überwiegend Bezirke 21 + 22):</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 44%">
<col style="width: 31%">
<col style="width: 24%">
</colgroup>
<thead>
<tr class="header">
<th>Algorithmus</th>
<th style="text-align: right;">Treffer</th>
<th style="text-align: right;">Quote</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Baseline — exakter Join (vor #37)</td>
<td style="text-align: right;">1.661</td>
<td style="text-align: right;">81,5 %</td>
</tr>
<tr class="even">
<td>Fix A + Fix B (nach #37)</td>
<td style="text-align: right;">1.921</td>
<td style="text-align: right;">94,2 %</td>
</tr>
<tr class="odd">
<td><strong>Fix A + Fix B + Fix C REST API (nach #48)</strong></td>
<td style="text-align: right;"><strong>1.976</strong></td>
<td style="text-align: right;"><strong>96,9 %</strong></td>
</tr>
</tbody>
</table>
<p>Fix C hat 55 der 118 verbleibenden nicht gefundenen Zeilen (46,6 % der Restzahl) in 4 Sekunden bei Parallelität 8 aufgelöst. Die verbleibenden 63 Zeilen haben keinen Treffer im Live-Wiener Adressregister. Siehe <code>analysis/qa/upload_match_rate_post_c.md</code> für den vollständigen Bericht.</p>
<p>Fix A (nächstgelegene Hausnummer) erholt 246 Zeilen (12,1 Pp.). Fix B (zusammengesetzte Straße) erholt 14 Zeilen (0,7 Pp.). Die verbleibenden 118 nicht gefundenen Adressen sind überwiegend Schrebergarten-Parzellen und Straßen, die in ADRESSENOGD nicht enthalten sind.</p>
<p>Alle Zeiten gelten für die DuckDB-WASM-Abfragephase nach dem Aufwärmen. Der Fuzzy-Fallback fügt bei nicht gefundenen Zeilen eine zweite Abfrage hinzu — bei guter Trefferquote auf dem ersten Durchlauf kaum spürbar.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Zeilen</th>
<th>Vorgang</th>
<th>Geschätzte Zeit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>12 (Beispiel)</td>
<td>Eine DuckDB-Verknüpfung</td>
<td>&lt;100 ms nach Aufwärmen</td>
</tr>
<tr class="even">
<td>100</td>
<td>Eine DuckDB-Verknüpfung</td>
<td>&lt;200 ms</td>
</tr>
<tr class="odd">
<td>500</td>
<td>Eine DuckDB-Verknüpfung</td>
<td>&lt;300 ms</td>
</tr>
<tr class="even">
<td>2.000</td>
<td>Zwei DuckDB-Abfragen (exakt + Fuzzy)</td>
<td>~600 ms</td>
</tr>
<tr class="odd">
<td>10.000</td>
<td>Zwei DuckDB-Abfragen + CSV-Ausgabe</td>
<td>1,5–2,5 s</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="page-weight-seitengröße" class="level3">
<h3 class="anchored" data-anchor-id="page-weight-seitengröße">Page weight / Seitengröße</h3>
<div data-lang="en">
<p>All sizes are gzipped estimates. The Parquet file is range-fetched via predicate pushdown — the browser does not download all 15.7 MB per query.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 64%">
<col style="width: 35%">
</colgroup>
<thead>
<tr class="header">
<th>Component</th>
<th>Size</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>HTML shell (upload.qmd render)</td>
<td>~45 KB</td>
</tr>
<tr class="even">
<td>PapaParse (CDN)</td>
<td>~14 KB</td>
</tr>
<tr class="odd">
<td>SheetJS (CDN)</td>
<td>~90 KB</td>
</tr>
<tr class="even">
<td>DuckDB-WASM core (CDN, lazy-loaded on first query)</td>
<td>~3–4 MB</td>
</tr>
<tr class="odd">
<td>Chart.js (CDN)</td>
<td>~80 KB</td>
</tr>
<tr class="even">
<td>Address Parquet (<code>docs/data/addresses_2026-05-02.parquet</code>, range-fetched)</td>
<td>15.7 MB total; typically ~500 KB read per query via predicate pushdown</td>
</tr>
<tr class="odd">
<td><strong>Initial first-visit total</strong></td>
<td><strong>~4 MB</strong> (DuckDB warm-up dominates)</td>
</tr>
<tr class="even">
<td><strong>Repeat visit (cached)</strong></td>
<td><strong>~150 KB</strong></td>
</tr>
</tbody>
</table>
</div>
<div data-lang="de">
<p>Alle Größen sind gzip-komprimierte Schätzungen. Die Parquet-Datei wird per Predicate Pushdown range-abgerufen — der Browser lädt nicht alle 15,7 MB pro Abfrage.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 63%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th>Komponente</th>
<th>Größe</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>HTML-Gerüst (upload.qmd gerendert)</td>
<td>~45 KB</td>
</tr>
<tr class="even">
<td>PapaParse (CDN)</td>
<td>~14 KB</td>
</tr>
<tr class="odd">
<td>SheetJS (CDN)</td>
<td>~90 KB</td>
</tr>
<tr class="even">
<td>DuckDB-WASM-Kern (CDN, lazy beim ersten Aufruf)</td>
<td>~3–4 MB</td>
</tr>
<tr class="odd">
<td>Chart.js (CDN)</td>
<td>~80 KB</td>
</tr>
<tr class="even">
<td>Adressen-Parquet (<code>docs/data/addresses_2026-05-02.parquet</code>, range-fetch)</td>
<td>15,7 MB gesamt; typischerweise ~500 KB pro Abfrage via Predicate Pushdown</td>
</tr>
<tr class="odd">
<td><strong>Erster Besuch gesamt</strong></td>
<td><strong>~4 MB</strong> (DuckDB-Kaltstart dominiert)</td>
</tr>
<tr class="even">
<td><strong>Wiederholter Besuch (gecacht)</strong></td>
<td><strong>~150 KB</strong></td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="compatibility-kompatibilität" class="level3">
<h3 class="anchored" data-anchor-id="compatibility-kompatibilität">Compatibility / Kompatibilität</h3>
<div data-lang="en">
<table class="caption-top table">
<colgroup>
<col style="width: 59%">
<col style="width: 40%">
</colgroup>
<thead>
<tr class="header">
<th>Requirement</th>
<th>Needed?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Install anything</td>
<td>No</td>
</tr>
<tr class="even">
<td>Special browser</td>
<td>Modern (Chrome/Safari/Firefox/Edge 2020+) — needs <code>WebAssembly</code> and ES module support</td>
</tr>
<tr class="odd">
<td>Desktop required</td>
<td>No (works on phone)</td>
</tr>
<tr class="even">
<td>Internet</td>
<td>Yes, for CDN libraries and Parquet on first visit; cached after</td>
</tr>
</tbody>
</table>
</div>
<div data-lang="de">
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Voraussetzung</th>
<th>Erforderlich?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Software installieren</td>
<td>Nein</td>
</tr>
<tr class="even">
<td>Besonderer Browser</td>
<td>Modern (Chrome/Safari/Firefox/Edge 2020+) — benötigt <code>WebAssembly</code> und ES-Modul-Unterstützung</td>
</tr>
<tr class="odd">
<td>Desktop erforderlich</td>
<td>Nein (funktioniert am Handy)</td>
</tr>
<tr class="even">
<td>Internet</td>
<td>Ja, für CDN-Bibliotheken und Parquet beim ersten Besuch; danach gecacht</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="mobile" class="level3">
<h3 class="anchored" data-anchor-id="mobile">Mobile</h3>
<div data-lang="en">
<table class="caption-top table">
<colgroup>
<col style="width: 52%">
<col style="width: 47%">
</colgroup>
<thead>
<tr class="header">
<th>Concern</th>
<th>Answer</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Browser support</td>
<td>All modern mobile browsers</td>
</tr>
<tr class="even">
<td>Screen size</td>
<td>Functional; results table needs horizontal scroll</td>
</tr>
<tr class="odd">
<td>Processing</td>
<td>Fine — DuckDB-WASM runs in-browser, single query for any plausible upload size</td>
</tr>
<tr class="even">
<td>Offline</td>
<td>After first visit, partial — Parquet + libs cached; CDN libs may need network on first load</td>
</tr>
</tbody>
</table>
</div>
<div data-lang="de">
<table class="caption-top table">
<colgroup>
<col style="width: 43%">
<col style="width: 56%">
</colgroup>
<thead>
<tr class="header">
<th>Thema</th>
<th>Antwort</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Browser-Unterstützung</td>
<td>Alle modernen Mobilbrowser</td>
</tr>
<tr class="even">
<td>Bildschirmgröße</td>
<td>Nutzbar; Ergebnistabelle braucht horizontales Scrollen</td>
</tr>
<tr class="odd">
<td>Verarbeitung</td>
<td>Kein Problem — DuckDB-WASM läuft im Browser, eine Abfrage für jede sinnvolle Dateigröße</td>
</tr>
<tr class="even">
<td>Offline</td>
<td>Nach dem ersten Besuch eingeschränkt — Parquet + Bibliotheken gecacht; CDN-Bibliotheken benötigen beim ersten Laden Netzwerk</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="load-time-ladezeit" class="level3">
<h3 class="anchored" data-anchor-id="load-time-ladezeit">Load time / Ladezeit</h3>
<div data-lang="en">
<p>DuckDB cold-start dominates first-visit time. Subsequent page loads use the browser cache and are fast regardless of connection speed.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Network</th>
<th>First visit</th>
<th>Repeat (cached)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>4G mobile</td>
<td>~6–8 s (DuckDB cold-start dominates)</td>
<td>&lt;0.5 s</td>
</tr>
<tr class="even">
<td>Office WiFi</td>
<td>~2–3 s</td>
<td>Instant</td>
</tr>
<tr class="odd">
<td>Slow 3G</td>
<td>~15–20 s</td>
<td>&lt;1 s</td>
</tr>
</tbody>
</table>
</div>
<div data-lang="de">
<p>Der DuckDB-Kaltstart bestimmt die Ladezeit beim ersten Besuch. Folgende Seitenaufrufe nutzen den Browser-Cache und sind unabhängig von der Verbindungsgeschwindigkeit schnell.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Netzwerk</th>
<th>Erster Besuch</th>
<th>Wiederholter Besuch (gecacht)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>4G Mobilfunk</td>
<td>~6–8 s (DuckDB-Kaltstart dominiert)</td>
<td>&lt;0,5 s</td>
</tr>
<tr class="even">
<td>Büro-WLAN</td>
<td>~2–3 s</td>
<td>Sofort</td>
</tr>
<tr class="odd">
<td>Langsames 3G</td>
<td>~15–20 s</td>
<td>&lt;1 s</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="per-fix-details" class="level3">
<h3 class="anchored" data-anchor-id="per-fix-details">Per-fix details / Details je Verbesserung</h3>
<div data-lang="en">
<p>Each fix is documented with its assumptions, benefits, costs, and example addresses where it does and does not work. Fix C (REST API fallback) and Fix D (multi-unit dedup correctness) are both now active.</p>
</div>
<div data-lang="de">
<p>Jede Verbesserung ist mit ihren Annahmen, Vorteilen, Kosten und Beispieladressen dokumentiert. Fix C (REST API Fallback) und Fix D (Mehrfacheinheit-Deduplizierung, Korrektheit) sind jetzt beide aktiv.</p>
</div>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-5-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-1" role="tab" aria-controls="tabset-5-1" aria-selected="true" href="">Fix A — Fuzzy nearest house / Nächstgelegene Hausnummer</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-5-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-2" role="tab" aria-controls="tabset-5-2" aria-selected="false" href="">Fix B — Composite-street splitter / Zusammengesetzte Straße</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-5-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-3" role="tab" aria-controls="tabset-5-3" aria-selected="false" href="">Fix C — REST API fallback (aktiv / active)</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-5-4-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-4" role="tab" aria-controls="tabset-5-4" aria-selected="false" href="">Fix D — Multi-unit dedup (aktiv / active)</a></li></ul>
<div class="tab-content">
<div id="tabset-5-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-5-1-tab">
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" href="">Summary / Zusammenfassung</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false" href="">Assumptions / Annahmen</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-3" role="tab" aria-controls="tabset-1-3" aria-selected="false" href="">Benefits / Vorteile</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-4-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-4" role="tab" aria-controls="tabset-1-4" aria-selected="false" href="">Costs / Kosten</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-5-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-5" role="tab" aria-controls="tabset-1-5" aria-selected="false" href="">Works on / Funktioniert bei</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-6-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-6" role="tab" aria-controls="tabset-1-6" aria-selected="false" href="">Doesn’t work on / Funktioniert nicht bei</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<div data-lang="en">
<p>When <code>(PLZ, street_norm)</code> matches but the exact <code>house_norm</code> is absent from ADRESSENOGD, the algorithm falls back to the nearest registered house number on the same street. The numeric distance between the user’s house number and the nearest ADRESSENOGD house number is stored in the <code>house_distance</code> column so users can filter low-confidence results. Distance is capped at 20 — rows further than that remain <code>unmatched</code>.</p>
</div>
<div data-lang="de">
<p>Wenn <code>(PLZ, Straßennorm)</code> übereinstimmt, die exakte Hausnummer aber nicht in ADRESSENOGD enthalten ist, fällt der Algorithmus auf die nächstgelegene registrierte Hausnummer in derselben Straße zurück. Die numerische Distanz zwischen der eingegebenen und der gefundenen Hausnummer wird in der Spalte <code>house_distance</code> gespeichert, damit unsichere Ergebnisse herausgefiltert werden können. Abstände über 20 bleiben als <code>unmatched</code> erhalten.</p>
</div>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<div data-lang="en">
<ul>
<li>The nearest registered house number on the same street is a reasonable proxy for an unregistered parcel or new building.</li>
<li>A numeric distance of ≤ 20 is close enough to be useful; beyond that the result is likely a different building entirely.</li>
<li>The user’s house number contains a leading integer (e.g.&nbsp;<code>21</code>, <code>21a</code>). If the house number is a parcel code like <code>Parz 38</code>, no leading integer is extracted and the fuzzy pass is skipped.</li>
</ul>
</div>
<div data-lang="de">
<ul>
<li>Die nächstgelegene registrierte Hausnummer in derselben Straße ist ein vertretbarer Ersatz für ein nicht registriertes Grundstück oder ein neues Gebäude.</li>
<li>Ein numerischer Abstand von ≤ 20 ist nahe genug, um nützlich zu sein; darüber hinaus handelt es sich wahrscheinlich um ein anderes Gebäude.</li>
<li>Die Hausnummer des Nutzers enthält eine führende Ganzzahl (z. B. <code>21</code>, <code>21a</code>). Ist die Hausnummer ein Parzellen-Code wie <code>Parz 38</code>, wird kein Wert extrahiert und der Fuzzy-Durchlauf übersprungen.</li>
</ul>
</div>
</div>
<div id="tabset-1-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-3-tab">
<div data-lang="en">
<ul>
<li>Recovers <strong>246 rows (12.1 pp)</strong> on the 2,039-row test file.</li>
<li>Lifts overall match rate from <strong>81.5% → ~93.6%</strong> (Fix A alone).</li>
<li>No external API calls — runs entirely in DuckDB-WASM in the browser.</li>
<li><code>house_distance</code> column lets the user decide whether to trust the result.</li>
</ul>
</div>
<div data-lang="de">
<ul>
<li>Erholt <strong>246 Zeilen (12,1 Pp.)</strong> auf der 2.039-zeiligen Testdatei.</li>
<li>Hebt die Gesamttrefferquote von <strong>81,5 % auf ~93,6 %</strong> (nur Fix A).</li>
<li>Keine externen API-Aufrufe — läuft vollständig in DuckDB-WASM im Browser.</li>
<li>Die Spalte <code>house_distance</code> erlaubt es dem Nutzer, die Zuverlässigkeit selbst zu beurteilen.</li>
</ul>
</div>
</div>
<div id="tabset-1-4" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-4-tab">
<div data-lang="en">
<ul>
<li>Returns a <strong>neighbour’s ACD</strong>, not necessarily the user’s exact building. For buildings registered under a slightly different number (e.g.&nbsp;the city uses <code>21</code> while the user has <code>21a</code>), this is usually correct. For new construction on a vacant plot, the neighbour’s ACD may be wrong.</li>
<li>Adds a second DuckDB query for unmatched rows — adds ~100 ms on a 2,000-row file with ~18% unmatched rows.</li>
<li><code>house_distance</code> must be inspected manually to assess confidence.</li>
</ul>
</div>
<div data-lang="de">
<ul>
<li>Gibt die ACD eines <strong>Nachbargebäudes</strong> zurück, nicht zwingend die des gesuchten Gebäudes. Für Gebäude mit leicht abweichender Hausnummer (z. B. <code>21</code> statt <code>21a</code>) ist das meist korrekt. Bei Neubauten auf bisher unbebautem Grund kann die ACD eines Nachbarn falsch sein.</li>
<li>Fügt bei nicht gefundenen Zeilen eine zweite DuckDB-Abfrage hinzu — ca. +100 ms bei 2.000 Zeilen mit ~18 % nicht gefundenen Adressen.</li>
<li><code>house_distance</code> muss manuell geprüft werden, um die Zuverlässigkeit einzuschätzen.</li>
</ul>
</div>
</div>
<div id="tabset-1-5" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-5-tab">
<div data-lang="en">
<ul>
<li><code>1210, Achengasse, 21</code> — Achengasse 21 not in ADRESSENOGD; nearest is <code>Achengasse 19</code> (distance 2). ACD from <code>070268</code> block returned.</li>
<li><code>1210, Siemensstraße, 87</code> — if 87 is absent but 85 and 89 are present, distance 2, correct ACD returned.</li>
<li>Any street where the odd/even side of the street has gaps in registered house numbers.</li>
</ul>
</div>
<div data-lang="de">
<ul>
<li><code>1210, Achengasse, 21</code> — Achengasse 21 nicht in ADRESSENOGD; nächstgelegen ist <code>Achengasse 19</code> (Abstand 2). ACD aus dem Block <code>070268</code> wird zurückgegeben.</li>
<li><code>1210, Siemensstraße, 87</code> — wenn 87 fehlt, aber 85 und 89 vorhanden sind, Abstand 2, korrekte ACD.</li>
<li>Jede Straße, bei der die gerade oder ungerade Seite Lücken in den registrierten Hausnummern hat.</li>
</ul>
</div>
</div>
<div id="tabset-1-6" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-6-tab">
<div data-lang="en">
<ul>
<li><strong>Parcel codes</strong> (<code>Parz 38</code>, <code>Parz 12b</code>) — no leading integer, fuzzy pass skipped; remains <code>unmatched</code>.</li>
<li><strong>New buildings</strong> not yet in ADRESSENOGD at all — the street is present but all house numbers are far from the user’s. If the nearest is &gt; 20 away, remains <code>unmatched</code>.</li>
<li><strong>Streets genuinely absent</strong> from ADRESSENOGD (35% of the unmatched cohort on the test file) — no candidate rows to compare against.</li>
</ul>
</div>
<div data-lang="de">
<ul>
<li><strong>Parzellen-Codes</strong> (<code>Parz 38</code>, <code>Parz 12b</code>) — keine führende Ganzzahl, Fuzzy-Durchlauf übersprungen; bleibt <code>unmatched</code>.</li>
<li><strong>Neubauten</strong>, die noch nicht in ADRESSENOGD erfasst sind — Straße vorhanden, aber alle Hausnummern sind weit entfernt. Bei Abstand &gt; 20 bleibt der Eintrag <code>unmatched</code>.</li>
<li><strong>Straßen, die gar nicht in ADRESSENOGD</strong> enthalten sind (35 % der nicht gefundenen Zeilen in der Testdatei) — keine Kandidaten für den Vergleich.</li>
</ul>
</div>
</div>
</div>
</div>
</div>
<div id="tabset-5-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-5-2-tab">
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-2-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-1" role="tab" aria-controls="tabset-2-1" aria-selected="true" href="">Summary / Zusammenfassung</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-2" role="tab" aria-controls="tabset-2-2" aria-selected="false" href="">Assumptions / Annahmen</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-3" role="tab" aria-controls="tabset-2-3" aria-selected="false" href="">Benefits / Vorteile</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-4-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-4" role="tab" aria-controls="tabset-2-4" aria-selected="false" href="">Costs / Kosten</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-5-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-5" role="tab" aria-controls="tabset-2-5" aria-selected="false" href="">Works on / Funktioniert bei</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-6-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-6" role="tab" aria-controls="tabset-2-6" aria-selected="false" href="">Doesn’t work on / Funktioniert nicht bei</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-2-1-tab">
<div data-lang="en">
<p>Some Vienna addresses identify corner parcels with two street names joined by <code>/</code>, e.g.&nbsp;<code>Achengasse 4/Lavantgasse 1a</code>. The previous implementation claimed to handle these but the split was not being applied before the main JOIN, so no recovery occurred. Fix B reimplements the splitter in JavaScript <em>before</em> the JOIN: each <code>A/B</code> street is expanded into two sub-rows, each looked up independently. The results are aggregated as <code>acd_b</code> (second match) and <code>match_quality = "split_both"</code> (both matched) or <code>"split_partial"</code> (one matched).</p>
</div>
<div data-lang="de">
<p>Manche Wiener Adressen bezeichnen Eckgrundstücke mit zwei durch <code>/</code> verbundenen Straßennamen, z. B. <code>Achengasse 4/Lavantgasse 1a</code>. Die frühere Implementierung behauptete, diese zu verarbeiten, aber die Aufteilung fand vor dem JOIN nicht statt. Fix B reimplementiert den Splitter in JavaScript <em>vor</em> dem JOIN: Jede <code>A/B</code>-Adresse wird in zwei Teilzeilen aufgeteilt, die unabhängig voneinander nachgeschlagen werden. Die Ergebnisse werden als <code>acd_b</code> (zweiter Treffer) und <code>match_quality = "split_both"</code> (beide gefunden) oder <code>"split_partial"</code> (einer gefunden) zusammengeführt.</p>
</div>
</div>
<div id="tabset-2-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-2-tab">
<div data-lang="en">
<ul>
<li>A <code>/</code> in the street column indicates a composite address identifying the same physical location from two streets (corner building or shared driveway).</li>
<li>A trailing number in each half of the split is the house number for that half, e.g.&nbsp;<code>Achengasse 4</code> → street <code>Achengasse</code>, house <code>4</code>.</li>
<li>Both ACDs are valid for the same physical building; the user can choose either.</li>
</ul>
</div>
<div data-lang="de">
<ul>
<li>Ein <code>/</code> in der Straßenspalte bezeichnet eine zusammengesetzte Adresse, die denselben physischen Standort von zwei Straßen aus beschreibt (Eckgebäude oder gemeinsame Zufahrt).</li>
<li>Eine abschließende Zahl in jeder Hälfte des Splits ist die Hausnummer für diese Hälfte, z. B. <code>Achengasse 4</code> → Straße <code>Achengasse</code>, Hausnummer <code>4</code>.</li>
<li>Beide ACDs sind für dasselbe physische Gebäude gültig; der Nutzer kann eine davon wählen.</li>
</ul>
</div>
</div>
<div id="tabset-2-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-3-tab">
<div data-lang="en">
<ul>
<li>Recovers <strong>14 rows (0.7 pp)</strong> on the 2,039-row test file.</li>
<li>Returns both ACDs when both halves resolve, giving the user the full picture for corner parcels.</li>
<li>No distance estimation needed — the result is exact if the street+house exists in ADRESSENOGD.</li>
</ul>
</div>
<div data-lang="de">
<ul>
<li>Erholt <strong>14 Zeilen (0,7 Pp.)</strong> auf der 2.039-zeiligen Testdatei.</li>
<li>Gibt beide ACDs zurück, wenn beide Hälften aufgelöst werden, und liefert dem Nutzer das vollständige Bild für Eckgrundstücke.</li>
<li>Keine Abstandsschätzung erforderlich — das Ergebnis ist exakt, wenn Straße + Hausnummer in ADRESSENOGD vorhanden sind.</li>
</ul>
</div>
</div>
<div id="tabset-2-4" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-4-tab">
<div data-lang="en">
<ul>
<li>Returning two ACDs (<code>ACD</code> + <code>acd_b</code>) requires the user to inspect both columns for composite matches.</li>
<li>Pure Schrebergarten parcel addresses like <code>Parz 38</code> remain unmatched even after the split because neither half maps to a registered building address.</li>
<li>Expands input rows before the JOIN — minor overhead proportional to the number of composite rows in the upload file.</li>
</ul>
</div>
<div data-lang="de">
<ul>
<li>Die Rückgabe zweier ACDs (<code>ACD</code> + <code>acd_b</code>) erfordert, dass der Nutzer beide Spalten bei zusammengesetzten Treffern prüft.</li>
<li>Reine Schrebergarten-Parzellenadressen wie <code>Parz 38</code> bleiben auch nach dem Split nicht gefunden, da keine Hälfte einer registrierten Gebäudeadresse entspricht.</li>
<li>Eingabezeilen werden vor dem JOIN erweitert — geringer Mehraufwand proportional zur Anzahl der zusammengesetzten Zeilen.</li>
</ul>
</div>
</div>
<div id="tabset-2-5" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-5-tab">
<div data-lang="en">
<ul>
<li><code>1210, Achengasse 4/Lavantgasse 1a, —</code> → ACD for <code>Achengasse 4</code> as <code>ACD</code>, ACD for <code>Lavantgasse 1a</code> as <code>acd_b</code>, <code>match_quality = "split_both"</code>.</li>
<li>Corner buildings where both street addresses are registered in ADRESSENOGD.</li>
<li>Any composite address where at least one half is a valid street+house combination in the reference data.</li>
</ul>
</div>
<div data-lang="de">
<ul>
<li><code>1210, Achengasse 4/Lavantgasse 1a, —</code> → ACD für <code>Achengasse 4</code> als <code>ACD</code>, ACD für <code>Lavantgasse 1a</code> als <code>acd_b</code>, <code>match_quality = "split_both"</code>.</li>
<li>Eckgebäude, bei denen beide Straßenadressen in ADRESSENOGD registriert sind.</li>
<li>Jede zusammengesetzte Adresse, bei der mindestens eine Hälfte eine gültige Straße-Hausnummer-Kombination in den Referenzdaten ist.</li>
</ul>
</div>
</div>
<div id="tabset-2-6" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-6-tab">
<div data-lang="en">
<ul>
<li><strong>Pure Schrebergarten parcels</strong> like <code>Achengasse/Lavantgasse Parz 38</code> — the parcel number does not correspond to a registered building address in ADRESSENOGD; both halves miss.</li>
<li>Composite strings where the separator has a different meaning (e.g. address range <code>1/3</code> meaning “houses 1 to 3” on a single street — these will be incorrectly split into two sub-lookups).</li>
<li>Very long composite strings with 3+ parts — only the first two are attempted.</li>
</ul>
</div>
<div data-lang="de">
<ul>
<li><strong>Reine Schrebergarten-Parzellen</strong> wie <code>Achengasse/Lavantgasse Parz 38</code> — die Parzellennummer entspricht keiner registrierten Gebäudeadresse in ADRESSENOGD; beide Hälften schlagen fehl.</li>
<li>Zusammengesetzte Zeichenketten, bei denen das Trennzeichen eine andere Bedeutung hat (z. B. Adressbereich <code>1/3</code> für „Hausnummern 1 bis 3” auf einer einzelnen Straße — diese werden fälschlicherweise in zwei Teilabfragen aufgeteilt).</li>
<li>Sehr lange zusammengesetzte Zeichenketten mit 3+ Teilen — nur die ersten beiden werden versucht.</li>
</ul>
</div>
</div>
</div>
</div>
</div>
<div id="tabset-5-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-5-3-tab">
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-3-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-1" role="tab" aria-controls="tabset-3-1" aria-selected="true" href="">Summary / Zusammenfassung</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-2" role="tab" aria-controls="tabset-3-2" aria-selected="false" href="">Assumptions / Annahmen</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-3" role="tab" aria-controls="tabset-3-3" aria-selected="false" href="">Benefits / Vorteile</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-4-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-4" role="tab" aria-controls="tabset-3-4" aria-selected="false" href="">Costs / Kosten</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-5-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-5" role="tab" aria-controls="tabset-3-5" aria-selected="false" href="">Works on / Funktioniert bei</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-6-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-6" role="tab" aria-controls="tabset-3-6" aria-selected="false" href="">Doesn’t work on / Funktioniert nicht bei</a></li></ul>
<div class="tab-content">
<div id="tabset-3-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-3-1-tab">
<div data-lang="en">
<p><strong>Status: ACTIVE</strong> — implemented in <a href="https://github.com/JohnGavin/acd_area_climate_design/issues/48">issue #48</a>. For rows still unmatched after Fix A + Fix B, click the <strong>“🌐 Try REST API for residual unmatched”</strong> button that appears below the results. The page calls the city’s <a href="https://data.wien.gv.at/daten/OGDAddressService.svc/GetAddressInfo"><code>OGDAddressService.svc/GetAddressInfo</code></a> REST endpoint once per unmatched row. The API performs server-side fuzzy matching and returns the canonical ACD. Concurrency is capped at 8 parallel requests and a maximum of 250 calls per upload session to stay within polite use of the public OGD service. Matched rows receive <code>match_quality = "rest_api_fallback"</code>.</p>
<p>Target: ≥ 98% match rate on the 2,039-row test file (up from 94.2% after Fix A + Fix B).</p>
</div>
<div data-lang="de">
<p><strong>Status: AKTIV</strong> — umgesetzt in <a href="https://github.com/JohnGavin/acd_area_climate_design/issues/48">Issue #48</a>. Für nach Fix A + B noch nicht gefundene Zeilen erscheint unterhalb der Ergebnisse die Schaltfläche <strong>„🌐 REST API für verbleibende Adressen versuchen”</strong>. Die Seite ruft den städtischen REST-Endpunkt <a href="https://data.wien.gv.at/daten/OGDAddressService.svc/GetAddressInfo"><code>OGDAddressService.svc/GetAddressInfo</code></a> einmal pro nicht gefundener Zeile auf. Die API führt serverseitig eigenes Fuzzy-Matching durch und gibt die kanonische ACD zurück. Die Parallelität ist auf 8 gleichzeitige Anfragen und maximal 250 Aufrufe pro Sitzung begrenzt. Gefundene Zeilen erhalten <code>match_quality = "rest_api_fallback"</code>.</p>
<p>Ziel: ≥ 98 % Trefferquote auf der 2.039-zeiligen Testdatei (gegenüber 94,2 % nach Fix A + B).</p>
</div>
</div>
<div id="tabset-3-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-2-tab">
<div data-lang="en">
<ul>
<li>The city’s OGDAddressService API is publicly available without authentication and is subject to reasonable use; the 250-call session cap stays well within polite limits.</li>
<li>Round-trip time is approximately 200–500 ms per request; 8 concurrent requests cap total elapsed time to ≤ 30 s for 118 residual rows.</li>
<li>The API’s own matching is more permissive than our static Parquet snapshot for Schrebergarten parcel addresses and edge-case spellings.</li>
<li>The city’s JSON response schema is stable: <code>features[0].properties.ACD</code> and <code>features[0].properties.SCD</code> are present when a match is found. The <code>Ranking</code> property indicates the API’s internal match confidence.</li>
<li>Users accept that unmatched address fragments (street + house number only, no name or personal data) are sent to the OGD server when they click the button.</li>
</ul>
</div>
<div data-lang="de">
<ul>
<li>Der OGDAddressService-Endpunkt der Stadt Wien ist ohne Authentifizierung öffentlich verfügbar und für vernünftige Nutzung ausgelegt; das Sitzungslimit von 250 Aufrufen liegt weit innerhalb fairer Nutzung.</li>
<li>Die Roundtrip-Zeit beträgt ca. 200–500 ms pro Anfrage; 8 gleichzeitige Anfragen begrenzen die Gesamtdauer auf ≤ 30 s für 118 verbleibende Zeilen.</li>
<li>Das eigene Matching der API ist für Schrebergarten-Parzellenadressen und Sonderfälle großzügiger als unser statischer Parquet-Snapshot.</li>
<li>Das JSON-Antwortschema der Stadt ist stabil: <code>features[0].properties.ACD</code> und <code>features[0].properties.SCD</code> sind vorhanden, wenn ein Treffer gefunden wird. Die Eigenschaft <code>Ranking</code> gibt die interne Match-Konfidenz der API an.</li>
<li>Nutzer akzeptieren, dass nicht gefundene Adressfragmente (nur Straße und Hausnummer, keine Namen oder personenbezogenen Daten) an den OGD-Server gesendet werden, wenn sie die Schaltfläche drücken.</li>
</ul>
</div>
</div>
<div id="tabset-3-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-3-tab">
<div data-lang="en">
<ul>
<li>Expected to recover ~2–5 additional percentage points on top of Fix A + B, targeting ≥ 98% match rate on the test file.</li>
<li>Canonicalises multi-unit deduplication ambiguity for the rows it resolves, since the API returns the registered ACD directly.</li>
<li>No local data updates needed — the API always reflects the current live Wien address register, including newly built addresses not yet in our Parquet snapshot.</li>
<li>Completely optional: users who do not need the extra coverage, or who are offline, can skip the button and download the 94.2% result as-is.</li>
<li><code>rest_ranking</code> column exposes the API’s internal match score so users can filter low-confidence API matches.</li>
</ul>
</div>
<div data-lang="de">
<ul>
<li>Voraussichtlich ~2–5 weitere Prozentpunkte zusätzlich zu Fix A + B, mit dem Ziel einer Trefferquote von ≥ 98 % auf der Testdatei.</li>
<li>Kanonisiert Mehrdeutigkeiten bei Mehrfamilienhäusern für die gefundenen Zeilen, da die API die registrierte ACD direkt zurückgibt.</li>
<li>Keine lokalen Datenaktualisierungen erforderlich — die API spiegelt immer den aktuellen Stand des Wiener Adressregisters wider, einschließlich Neubauten, die noch nicht in unserem Parquet-Snapshot enthalten sind.</li>
<li>Vollständig optional: Nutzer, die keine zusätzliche Abdeckung benötigen oder offline sind, können die Schaltfläche überspringen und das 94,2%-Ergebnis herunterladen.</li>
<li>Die Spalte <code>rest_ranking</code> gibt den internen Match-Score der API zurück, damit unsichere API-Treffer herausgefiltert werden können.</li>
</ul>
</div>
</div>
<div id="tabset-3-4" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-4-tab">
<div data-lang="en">
<ul>
<li>Requires network connectivity for the fallback rows — not offline-capable for this step (Fix A + Fix B still run offline).</li>
<li>The city API may change its JSON schema or become temporarily unavailable without notice; errors are handled gracefully (<code>match_quality = "unmatched_after_rest"</code> on failure, no exception thrown).</li>
<li>Users must accept that unmatched address fragments (street + house number, no personal data) are sent to the external OGD server when the button is clicked. This is stated clearly in the UI.</li>
<li>Session budget is 250 calls; rows beyond the budget receive <code>match_quality = "rest_skipped_over_budget"</code> and are not sent.</li>
<li>CORS: the API must permit cross-origin requests from the GitHub Pages domain. Tested on the live URL — see the QA report for the result.</li>
</ul>
</div>
<div data-lang="de">
<ul>
<li>Erfordert Netzwerkzugang für die Fallback-Zeilen — dieser Schritt ist nicht offline nutzbar (Fix A + Fix B laufen weiterhin offline).</li>
<li>Das JSON-Schema der städtischen API kann sich ohne Vorankündigung ändern oder der Dienst kann vorübergehend ausfallen; Fehler werden sauber abgefangen (<code>match_quality = "unmatched_after_rest"</code> bei Fehler, keine Ausnahme).</li>
<li>Nutzer müssen akzeptieren, dass nicht gefundene Adressfragmente (Straße und Hausnummer, keine personenbezogenen Daten) beim Klick auf die Schaltfläche an den externen OGD-Server übertragen werden. Dies ist in der Benutzeroberfläche klar ersichtlich.</li>
<li>Das Sitzungsbudget beträgt 250 Aufrufe; Zeilen darüber erhalten <code>match_quality = "rest_skipped_over_budget"</code> und werden nicht übermittelt.</li>
<li>CORS: Die API muss Cross-Origin-Anfragen von der GitHub-Pages-Domain erlauben. Testergebnis: siehe QA-Bericht.</li>
</ul>
</div>
</div>
<div id="tabset-3-5" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-5-tab">
<div data-lang="en">
<ul>
<li><strong>Schrebergarten parcel addresses</strong> that the API maps to a registered base building address — e.g.&nbsp;<code>Kleingarten Aspern Parz 38</code> → nearest registered building in the same Kleingarten area.</li>
<li><strong>New buildings</strong> registered in the live Wien address register but not yet in our Parquet snapshot (snapshot date: 2026-05-02).</li>
<li><strong>Edge-case spellings</strong> the API normalises on the server side (umlauts, abbreviations, minor typos).</li>
<li>Any address where the city’s OGD service has a match even if our static join does not.</li>
</ul>
</div>
<div data-lang="de">
<ul>
<li><strong>Schrebergarten-Parzellenadressen</strong>, die die API einer registrierten Basisgebäudeadresse zuordnet — z. B. <code>Kleingarten Aspern Parz 38</code> → nächstgelegenes registriertes Gebäude im selben Kleingartenareal.</li>
<li><strong>Neubauten</strong>, die im Live-Adressregister Wien registriert sind, aber noch nicht in unserem Parquet-Snapshot enthalten sind (Stand: 2026-05-02).</li>
<li><strong>Sonderfallschreibweisen</strong>, die die API serverseitig normalisiert (Umlaute, Abkürzungen, kleinere Tippfehler).</li>
<li>Jede Adresse, für die der OGD-Dienst der Stadt einen Treffer hat, auch wenn unser statischer Join keinen findet.</li>
</ul>
</div>
</div>
<div id="tabset-3-6" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-6-tab">
<div data-lang="en">
<ul>
<li>Addresses with no match in the live Wien register either — these receive <code>match_quality = "unmatched_after_rest"</code>.</li>
<li>Offline use cases — the button requires an active internet connection.</li>
<li>Rows beyond the 250-call session budget — these receive <code>match_quality = "rest_skipped_over_budget"</code>.</li>
<li>CORS-blocked environments (e.g.&nbsp;certain corporate proxies that block cross-origin API calls to external domains).</li>
</ul>
</div>
<div data-lang="de">
<ul>
<li>Adressen, die auch im Live-Register Wien keinen Treffer haben — diese erhalten <code>match_quality = "unmatched_after_rest"</code>.</li>
<li>Offline-Anwendungsfälle — die Schaltfläche erfordert eine aktive Internetverbindung.</li>
<li>Zeilen, die das Sitzungsbudget von 250 Aufrufen überschreiten — diese erhalten <code>match_quality = "rest_skipped_over_budget"</code>.</li>
<li>CORS-blockierte Umgebungen (z. B. bestimmte Firmen-Proxys, die Cross-Origin-API-Aufrufe an externe Domains sperren).</li>
</ul>
</div>
</div>
</div>
</div>
</div>
<div id="tabset-5-4" class="tab-pane" role="tabpanel" aria-labelledby="tabset-5-4-tab">
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-4-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-1" role="tab" aria-controls="tabset-4-1" aria-selected="true" href="">Summary / Zusammenfassung</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-4-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-2" role="tab" aria-controls="tabset-4-2" aria-selected="false" href="">Assumptions / Annahmen</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-4-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-3" role="tab" aria-controls="tabset-4-3" aria-selected="false" href="">Benefits / Vorteile</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-4-4-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-4" role="tab" aria-controls="tabset-4-4" aria-selected="false" href="">Costs / Kosten</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-4-5-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-5" role="tab" aria-controls="tabset-4-5" aria-selected="false" href="">Works on / Funktioniert bei</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-4-6-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-6" role="tab" aria-controls="tabset-4-6" aria-selected="false" href="">Doesn’t work on / Funktioniert nicht bei</a></li></ul>
<div class="tab-content">
<div id="tabset-4-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-4-1-tab">
<div data-lang="en">
<p><strong>Status: ACTIVE</strong> — implemented in <a href="https://github.com/JohnGavin/acd_area_climate_design/issues/49">issue #49</a>.</p>
<p>ADRESSENOGD contains 291,823 rows but only 148,444 unique <code>(PLZ, street, house)</code> tuples. <strong>19,319 of those tuples (13.0%) have more than one ACD</strong> — multi-unit buildings, separate staircases (<code>Stiegen</code>), or sub-addresses. For example, <code>Achengasse 4, 1210</code> has 82 registered ACDs.</p>
<p>The previous page deduplicated on <code>(PLZ, street, house)</code> and returned one ACD arbitrarily — whichever sorted first. Fix D replaces that with a <code>GROUP BY + ARRAY_AGG</code> in the DuckDB-WASM <code>addr</code> VIEW. When multiple ACDs match an address:</p>
<ul>
<li><code>match_quality = "ambiguous_multi"</code> (shown in purple)</li>
<li><code>acd_count</code> column shows how many ACDs exist</li>
<li><code>acd_codes</code> column shows all ACDs comma-joined</li>
<li>The <strong>⚠ N units</strong> badge next to the ACD cell is clickable to reveal all codes</li>
<li>The CSV download offers a <strong>“All ACDs (one row per ACD)”</strong> mode that expands ambiguous rows with <code>acd_unit_index = 0..N-1</code> for join-back</li>
</ul>
<p>Match rate is unchanged — the 13% ambiguous rows were previously counted as “matched” (just silently wrong). What changes is honesty: the user now sees the ambiguity instead of receiving an arbitrary result.</p>
</div>
<div data-lang="de">
<p><strong>Status: AKTIV</strong> — umgesetzt in <a href="https://github.com/JohnGavin/acd_area_climate_design/issues/49">Issue #49</a>.</p>
<p>ADRESSENOGD enthält 291.823 Zeilen, aber nur 148.444 eindeutige <code>(PLZ, Straße, Haus)</code>-Tupel. <strong>19.319 dieser Tupel (13,0 %) haben mehr als eine ACD</strong> — Mehrfamilienhäuser, separate Stiegen oder Unteradressen. Zum Beispiel hat <code>Achengasse 4, 1210</code> 82 registrierte ACDs.</p>
<p>Die bisherige Seite deduplizierte auf <code>(PLZ, Straße, Haus)</code> und gab eine ACD willkürlich zurück — jeweils die, die nach Sortierung zuerst kam. Fix D ersetzt das durch ein <code>GROUP BY + ARRAY_AGG</code> in der DuckDB-WASM-View <code>addr</code>. Bei mehreren ACDs für eine Adresse:</p>
<ul>
<li><code>match_quality = "ambiguous_multi"</code> (lila hervorgehoben)</li>
<li>Spalte <code>acd_count</code>: Anzahl der übereinstimmenden ACDs</li>
<li>Spalte <code>acd_codes</code>: alle ACDs kommagetrennt</li>
<li>Das <strong>⚠ N units</strong>-Badge neben der ACD-Zelle ist klickbar und zeigt alle Codes</li>
<li>Der CSV-Download bietet den Modus <strong>„Alle ACDs (eine Zeile je ACD)“</strong>, der mehrdeutige Zeilen mit <code>acd_unit_index = 0..N-1</code> für einen Rück-Join aufklappt</li>
</ul>
<p>Die Trefferquote bleibt gleich — die 13 % mehrdeutigen Zeilen wurden bisher als „gefunden” gezählt (aber still falsch). Was sich ändert, ist die Ehrlichkeit: Der Nutzer sieht jetzt die Mehrdeutigkeit statt ein willkürliches Ergebnis.</p>
</div>
</div>
<div id="tabset-4-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-4-2-tab">
<div data-lang="en">
<ul>
<li>The user knows their own unit / <code>Stiege</code> and can use the <code>acd_codes</code> list or the expanded CSV to identify their specific ACD.</li>
<li>Returning multiple ACDs is strictly preferable to silently picking one at random. There is no failure mode — single-unit addresses are unaffected.</li>
<li>The 13.0% figure (19,319 / 148,444 unique tuples) is based on the <code>addresses_2026-05-02.parquet</code> snapshot. The fraction is stable over time because it reflects Vienna’s physical building stock.</li>
<li><code>ARRAY_AGG(ACD ORDER BY ACD)</code> is deterministic: the list is sorted alphabetically, so <code>acd_list[1]</code> (the backward-compatible primary ACD) is always the lexicographically smallest ACD — not random.</li>
</ul>
</div>
<div data-lang="de">
<ul>
<li>Der Nutzer kennt seine eigene Einheit / Stiege und kann die Liste in <code>acd_codes</code> oder das aufgeklappte CSV nutzen, um seine spezifische ACD zu identifizieren.</li>
<li>Mehrere ACDs zurückzugeben ist einer willkürlichen Einzelauswahl eindeutig vorzuziehen. Es gibt keinen Fehlerfall — Einzeladressen sind unberührt.</li>
<li>Der Anteil von 13,0 % (19.319 / 148.444 eindeutige Tupel) basiert auf dem Snapshot <code>addresses_2026-05-02.parquet</code>. Er ist über die Zeit stabil, da er den physischen Gebäudebestand Wiens widerspiegelt.</li>
<li><code>ARRAY_AGG(ACD ORDER BY ACD)</code> ist deterministisch: Die Liste ist alphabetisch sortiert, <code>acd_list[1]</code> (die abwärtskompatible primäre ACD) ist immer die lexikografisch kleinste ACD — nicht zufällig.</li>
</ul>
</div>
</div>
<div id="tabset-4-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-4-3-tab">
<div data-lang="en">
<ul>
<li>Eliminates a hidden correctness bug affecting ~13% of matched rows.</li>
<li>No extra queries — the information is already in ADRESSENOGD; <code>GROUP BY</code> replaces <code>DISTINCT</code> at no additional cost.</li>
<li>Match rate is unchanged (≥ 96.9%); correctness improves for the 13% ambiguous cohort.</li>
<li><code>acd_codes</code> column gives the user the full picture to look up their unit.</li>
<li>CSV “All ACDs” mode preserves all valid options for downstream processing.</li>
</ul>
</div>
<div data-lang="de">
<ul>
<li>Beseitigt einen versteckten Korrektheitsfehler, der ~13 % der Treffer betrifft.</li>
<li>Keine zusätzlichen Abfragen — die Information ist schon in ADRESSENOGD; <code>GROUP BY</code> ersetzt <code>DISTINCT</code> ohne Mehraufwand.</li>
<li>Trefferquote bleibt unverändert (≥ 96,9 %); Korrektheit verbessert sich für die 13 % mehrdeutigen Adressen.</li>
<li>Spalte <code>acd_codes</code> gibt dem Nutzer alle Optionen für die Einheitensuche.</li>
<li>Der CSV-Modus „Alle ACDs” erhält alle gültigen Optionen für die Weiterverarbeitung.</li>
</ul>
</div>
</div>
<div id="tabset-4-4" class="tab-pane" role="tabpanel" aria-labelledby="tabset-4-4-tab">
<div data-lang="en">
<ul>
<li>CSV row-count exceeds input-row-count in “All ACDs” mode for multi-unit rows. Users expecting a strict 1:1 output should use “First ACD only” (default).</li>
<li>The <code>acd_list</code> object from DuckDB-WASM requires array unpacking in JavaScript; handled transparently, but adds a small deserialization step.</li>
<li>Column <code>acd_b</code> (Fix B composite-street second ACD) and <code>acd_codes</code> (Fix D all-units list) are conceptually different and both present in the output. Documentation makes the distinction clear.</li>
</ul>
</div>
<div data-lang="de">
<ul>
<li>Im Modus „Alle ACDs” überschreitet die CSV-Zeilenanzahl die Eingabezeilenanzahl bei Mehrfamilienhaus-Zeilen. Nutzer, die eine strikte 1:1-Ausgabe erwarten, sollten „Nur erste ACD” (Standard) verwenden.</li>
<li>Das <code>acd_list</code>-Objekt aus DuckDB-WASM erfordert Array-Entpackung in JavaScript; wird transparent verarbeitet, fügt aber einen kleinen Deserialisierungsschritt hinzu.</li>
<li>Die Spalten <code>acd_b</code> (Fix B: zweite ACD bei zusammengesetzter Adresse) und <code>acd_codes</code> (Fix D: alle Einheiten-ACDs) sind konzeptuell verschieden, aber beide in der Ausgabe vorhanden. Die Dokumentation macht den Unterschied klar.</li>
</ul>
</div>
</div>
<div id="tabset-4-5" class="tab-pane" role="tabpanel" aria-labelledby="tabset-4-5-tab">
<div data-lang="en">
<ul>
<li><strong>Any matched address in a multi-unit building.</strong> Example: <code>Achengasse 4, 1210</code> has 82 registered ACDs — all 82 are returned in <code>acd_codes</code>; the badge shows “⚠ 82 units”.</li>
<li><strong>All match quality levels</strong> that produce a match (<code>exact</code> → upgraded to <code>ambiguous_multi</code> when <code>acd_count &gt; 1</code>; similarly for <code>fuzzy_nearest_house</code>).</li>
<li><strong>Backward compatibility:</strong> <code>ACD</code> column still contains the first (lowest lexicographic) ACD, so existing downstream code reading only the <code>ACD</code> column continues to work.</li>
</ul>
</div>
<div data-lang="de">
<ul>
<li><strong>Jede gefundene Adresse in einem Mehrfamilienhaus.</strong> Beispiel: <code>Achengasse 4, 1210</code> hat 82 registrierte ACDs — alle 82 werden in <code>acd_codes</code> zurückgegeben; das Badge zeigt „⚠ 82 units”.</li>
<li><strong>Alle Treffer-Qualitätsstufen</strong>, die einen Treffer erzeugen (<code>exact</code> → aufgewertet zu <code>ambiguous_multi</code> bei <code>acd_count &gt; 1</code>; ebenso für <code>fuzzy_nearest_house</code>).</li>
<li><strong>Abwärtskompatibilität:</strong> Die Spalte <code>ACD</code> enthält weiterhin die erste (lexikografisch kleinste) ACD, sodass bestehender Code, der nur die <code>ACD</code>- Spalte liest, weiterhin funktioniert.</li>
</ul>
</div>
</div>
<div id="tabset-4-6" class="tab-pane" role="tabpanel" aria-labelledby="tabset-4-6-tab">
<div data-lang="en">
<ul>
<li><strong>Single-unit addresses</strong> — no change in behaviour (<code>acd_count = 1</code>, <code>match_quality = "exact"</code>, no badge shown).</li>
<li><strong>Unmatched addresses</strong> — Fix D only affects rows that do match; unmatched rows remain <code>match_quality = "unmatched"</code>.</li>
<li><strong>Unit-level disambiguation</strong> — Fix D tells the user there are N ACDs for their address, but does not know which unit is theirs. The user must look up their <code>Stiege</code> / door number in the <code>acd_codes</code> list or use the city’s <a href="https://www.wien.gv.at/adressensuche/">Adressensuche Wien</a> to confirm.</li>
</ul>
</div>
<div data-lang="de">
<ul>
<li><strong>Einzeladressen</strong> — keine Verhaltensänderung (<code>acd_count = 1</code>, <code>match_quality = "exact"</code>, kein Badge).</li>
<li><strong>Nicht gefundene Adressen</strong> — Fix D betrifft nur Treffer; nicht gefundene Adressen bleiben <code>match_quality = "unmatched"</code>.</li>
<li><strong>Einheiten-genaue Disambiguierung</strong> — Fix D teilt dem Nutzer mit, dass N ACDs für seine Adresse existieren, weiß aber nicht, welche Einheit gemeint ist. Der Nutzer muss seine Stiege / Türnummer in der Liste <code>acd_codes</code> nachschlagen oder die städtische <a href="https://www.wien.gv.at/adressensuche/">Adressensuche Wien</a> nutzen.</li>
</ul>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<!-- ── duckdb-wasm + lookup JS ─────────────────────────────────────────────── -->

<!-- Inline Chart.js for the per-district bar chart (no server needed) -->
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.3/dist/chart.umd.min.js"></script>

<script type="module">
// ── NOTE ON SQL USAGE ──────────────────────────────────────────────────────
// The `await conn.query("...")` calls below are duckdb-wasm's JS API.
// This is the idiomatic interface for duckdb-wasm; there is no JS equivalent
// of the R-side duckplyr package. The duckdplyr-not-sql rule applies to R code
// only. All R-side data access in this package uses duckplyr verbs.
// ──────────────────────────────────────────────────────────────────────────

import * as duckdb from "https://cdn.jsdelivr.net/npm/@duckdb/duckdb-wasm@1.29.0/+esm";

// ── Constants ──────────────────────────────────────────────────────────────
const PARQUET_URL =
  "https://johngavin.github.io/acd_area_climate_design/data/addresses_2026-05-02.parquet";

// Max numeric house-number distance for fuzzy fallback (Fix A).
// Rows whose nearest house is further than this remain 'unmatched'.
const FUZZY_MAX_DISTANCE = 20;

// ── State ──────────────────────────────────────────────────────────────────
let parsedRows   = [];   // [{PLZ, Strasse, HausNr, ...original cols}]
let resultRows   = [];   // full result after JOIN
let colHeaders   = [];   // original column names from user file
let dbConn       = null; // duckdb-wasm connection (lazy init)
let dbReady      = false;

// ── Utility ────────────────────────────────────────────────────────────────
function setProgress(pct, msg) {
  const sec = document.getElementById("progress-section");
  const bar = document.getElementById("progress-bar");
  const txt = document.getElementById("progress-msg");
  sec.style.display = pct < 100 ? "block" : "none";
  bar.style.width   = pct + "%";
  txt.textContent   = msg || "";
}

function escSql(s) {
  return String(s ?? "").replace(/'/g, "''");
}

// Extract the leading integer from a house-number string, e.g. "21a" → 21.
// Returns null if no integer found.
function extractLeadingInt(s) {
  const m = String(s ?? "").match(/^(\d+)/);
  return m ? parseInt(m[1], 10) : null;
}

// ── Fix B — Composite-street splitter ────────────────────────────────────
// For rows where Strasse contains "/" split into 1-2 sub-rows, each with
// composite_index and composite_total markers so mergeResults can identify
// which were from the same original row.
//
// "Achengasse 4/Lavantgasse 1a"  →  ["Achengasse 4", "Lavantgasse 1a"]
// Each side: attempt to pull a trailing number as the house number fallback.
function extractTrailingNumber(s) {
  const m = String(s ?? "").match(/(\d+\w*)$/);
  return m ? m[1] : null;
}

function splitComposite(rows, plzCol, streetCol, houseCol) {
  // Returns expanded array with extra fields:
  //   composite_index  — 0 for non-composite rows, 0/1/... for split parts
  //   composite_total  — 1 for non-composite, 2+ for split rows
  //   orig_idx         — index into original rows array
  //   PLZ, strasse_norm, hausnr_norm, garden_plot (same as before)
  const out = [];
  rows.forEach((r, idx) => {
    const plz    = String(r[plzCol]    ?? "").trim();
    const street = String(r[streetCol] ?? "").trim();
    const house  = String(r[houseCol]  ?? "").trim();
    const isParz = /parz/i.test(house);

    if (street.includes("/")) {
      const parts = street.split("/").map(s => s.trim()).filter(Boolean);
      parts.forEach((part, i) => {
        // If the part includes a trailing number use it as the house number
        const trailingNr = extractTrailingNumber(part);
        // Strip trailing number from street name to get clean street
        const streetOnly = part.replace(/\s*\d+\w*$/, "").trim();
        out.push({
          PLZ:              plz,
          strasse_norm:     streetOnly.toLowerCase(),
          hausnr_norm:      (trailingNr || house).toLowerCase(),
          garden_plot:      true,
          composite_index:  i,
          composite_total:  parts.length,
          orig_idx:         idx
        });
      });
    } else {
      out.push({
        PLZ:              plz,
        strasse_norm:     street.toLowerCase(),
        hausnr_norm:      house.toLowerCase(),
        garden_plot:      isParz,
        composite_index:  0,
        composite_total:  1,
        orig_idx:         idx
      });
    }
  });
  return out;
}

// ── DuckDB-Wasm init ───────────────────────────────────────────────────────
async function initDuck() {
  if (dbReady) return;
  setProgress(5, "Loading DuckDB-Wasm…");
  const BUNDLES = duckdb.getJsDelivrBundles();
  const bundle  = await duckdb.selectBundle(BUNDLES);
  const worker  = await duckdb.createWorker(bundle.mainWorker);
  const logger  = new duckdb.ConsoleLogger();
  const db      = new duckdb.AsyncDuckDB(logger, worker);
  await db.instantiate(bundle.mainModule);
  dbConn  = await db.connect();

  setProgress(15, "Installing httpfs extension…");
  await dbConn.query("INSTALL httpfs; LOAD httpfs;");

  setProgress(25, "Registering address Parquet view…");
  // Fix D: GROUP BY (plz_norm, street_norm, house_norm) instead of keeping an
  // arbitrary first row.  ARRAY_AGG collects all ACDs for multi-unit buildings
  // so the UI can surface ambiguity instead of silently picking one ACD.
  await dbConn.query(`
    CREATE OR REPLACE VIEW addr AS
    SELECT
      CAST(PLZ AS VARCHAR)                         AS plz_norm,
      LOWER(TRIM(NAME_STR))                        AS street_norm,
      LOWER(TRIM(NAME_ONR))                        AS house_norm,
      ARRAY_AGG(ACD           ORDER BY ACD)        AS acd_list,
      ARRAY_AGG(SCD_NAME_STR  ORDER BY ACD)        AS scd_list,
      ARRAY_AGG(STRABS_ZUGANG_STR ORDER BY ACD)    AS strabs_list,
      ARRAY_AGG(OBJEKT_ID     ORDER BY ACD)        AS objekt_id_list,
      ANY_VALUE(lon)                               AS lon,
      ANY_VALUE(lat)                               AS lat,
      COUNT(*)                                     AS acd_count
    FROM read_parquet('${PARQUET_URL}')
    GROUP BY
      CAST(PLZ AS VARCHAR),
      LOWER(TRIM(NAME_STR)),
      LOWER(TRIM(NAME_ONR))
  `);
  dbReady = true;
  setProgress(35, "Address lookup ready.");
}

// ── Run the JOIN (exact pass) ──────────────────────────────────────────────
// Returns array of result objects, one per expanded row.
// Rows that didn't match have ACD = null and match_quality = 'unmatched'.
async function runExactLookup(expanded) {
  // Build VALUES list: include composite_index and composite_total
  const vals = expanded
    .map(r => `('${escSql(r.PLZ)}','${escSql(r.strasse_norm)}','${escSql(r.hausnr_norm)}',${r.garden_plot ? 1 : 0},${r.composite_index},${r.composite_total},${r.orig_idx})`)
    .join(",\n");

  setProgress(55, "Creating user input table…");
  await dbConn.query("DROP TABLE IF EXISTS user_in");
  await dbConn.query(`
    CREATE TABLE user_in (
      plz_in           VARCHAR,
      street_in        VARCHAR,
      house_in         VARCHAR,
      garden_plot      INTEGER,
      composite_index  INTEGER,
      composite_total  INTEGER,
      orig_idx         INTEGER
    )
  `);
  await dbConn.query(`INSERT INTO user_in VALUES ${vals}`);

  // Also add a row_id column for the fuzzy pass to reference
  await dbConn.query(`
    ALTER TABLE user_in ADD COLUMN row_id INTEGER DEFAULT 0
  `);
  await dbConn.query(`
    UPDATE user_in SET row_id = rowid
  `);

  setProgress(70, "Joining against ADRESSENOGD (exact pass)…");
  // Fix D: addr view now has acd_list (ARRAY), acd_count (INTEGER) instead of
  // individual ACD/SCD_NAME_STR/... columns.  We expose the first element as
  // the primary ACD for backward compatibility, plus the full list and count.
  const res = await dbConn.query(`
    SELECT
      u.orig_idx,
      u.row_id,
      u.plz_in,
      u.street_in,
      u.house_in,
      u.garden_plot,
      u.composite_index,
      u.composite_total,
      a.acd_list[1]        AS ACD,
      a.scd_list[1]        AS SCD,
      a.strabs_list[1]     AS STRABS,
      a.objekt_id_list[1]  AS OBJEKT_ID,
      a.lon,
      a.lat,
      a.acd_list           AS acd_list,
      a.acd_count          AS acd_count,
      NULL::INTEGER        AS house_distance,
      CASE
        WHEN a.acd_list IS NULL THEN 'unmatched'
        WHEN a.acd_count > 1   THEN 'ambiguous_multi'
        ELSE 'exact'
      END AS match_quality
    FROM user_in u
    LEFT JOIN addr a
      ON u.plz_in    = a.plz_norm
     AND u.street_in = a.street_norm
     AND u.house_in  = a.house_norm
    ORDER BY u.orig_idx, u.composite_index
  `);

  return res.toArray().map(r => {
    // acd_list comes back as a DuckDB Vector/Array object — convert to plain JS array
    let acdArr = [];
    try {
      const raw = r.acd_list;
      if (raw != null) {
        if (typeof raw.toArray === "function") {
          acdArr = raw.toArray().map(String);
        } else if (Array.isArray(raw)) {
          acdArr = raw.map(String);
        } else {
          acdArr = [String(raw)];
        }
      }
    } catch (_) { /* leave empty */ }

    return {
      orig_idx:         Number(r.orig_idx),
      row_id:           Number(r.row_id),
      plz_in:           r.plz_in,
      street_in:        r.street_in,
      house_in:         r.house_in,
      garden_plot:      r.garden_plot === 1,
      composite_index:  Number(r.composite_index),
      composite_total:  Number(r.composite_total),
      ACD:              r.ACD,
      SCD:              r.SCD,
      STRABS:           r.STRABS,
      OBJEKT_ID:        r.OBJEKT_ID,
      lon:              r.lon,
      lat:              r.lat,
      house_distance:   null,
      acd_list:         acdArr,
      acd_count:        r.acd_count != null ? Number(r.acd_count) : null,
      match_quality:    r.match_quality
    };
  });
}

// ── Fix A — Fuzzy nearest-house fallback ──────────────────────────────────
// For rows that didn't match exactly, attempt to find the nearest house
// number on the same (PLZ, street_norm) combination.
// Only applies to non-composite rows where the street IS in ADRESSENOGD
// (i.e. the failure is a missing house number, not a missing street).
async function runFuzzyFallback(exactResults) {
  const unmatched = exactResults.filter(
    r => r.match_quality === "unmatched" && r.composite_total === 1
  );
  if (unmatched.length === 0) return exactResults;

  setProgress(75, "Fuzzy house-number fallback (Fix A)…");

  // Build VALUES for unmatched rows: (row_id, plz_in, street_in, house_in)
  const vals = unmatched
    .map(r => `(${r.row_id},'${escSql(r.plz_in)}','${escSql(r.street_in)}','${escSql(r.house_in)}')`)
    .join(",\n");

  await dbConn.query("DROP TABLE IF EXISTS unmatched_in");
  await dbConn.query(`
    CREATE TABLE unmatched_in (
      row_id    INTEGER,
      plz_in    VARCHAR,
      street_in VARCHAR,
      house_in  VARCHAR
    )
  `);
  await dbConn.query(`INSERT INTO unmatched_in VALUES ${vals}`);

  // Fuzzy query: for each unmatched row, find the nearest registered house
  // on the same (PLZ, street).  Uses a portable CTE + WHERE rn = 1 subquery
  // (avoids QUALIFY which is not supported in all duckdb-wasm builds).
  // ROW_NUMBER() OVER (PARTITION BY … ORDER BY …) IS fully supported.
  // Fix D: addr view now exposes acd_list[1]/scd_list[1]/... instead of
  // individual ACD/SCD_NAME_STR/STRABS_ZUGANG_STR/OBJEKT_ID columns.
  let fuzzy;
  try {
    fuzzy = await dbConn.query(`
      WITH candidates AS (
        SELECT
          u.row_id,
          a.acd_list[1]       AS ACD,
          a.scd_list[1]       AS SCD,
          a.strabs_list[1]    AS STRABS,
          a.objekt_id_list[1] AS OBJEKT_ID,
          a.lon,
          a.lat,
          a.acd_list          AS acd_list,
          a.acd_count         AS acd_count,
          ABS(
            COALESCE(TRY_CAST(REGEXP_EXTRACT(u.house_in,  '[0-9]+', 0) AS INTEGER), -9999) -
            COALESCE(TRY_CAST(REGEXP_EXTRACT(a.house_norm, '[0-9]+', 0) AS INTEGER), -9999)
          ) AS house_distance,
          ROW_NUMBER() OVER (
            PARTITION BY u.row_id
            ORDER BY ABS(
              COALESCE(TRY_CAST(REGEXP_EXTRACT(u.house_in,  '[0-9]+', 0) AS INTEGER), -9999) -
              COALESCE(TRY_CAST(REGEXP_EXTRACT(a.house_norm, '[0-9]+', 0) AS INTEGER), -9999)
            )
          ) AS rn
        FROM unmatched_in u
        JOIN addr a ON u.plz_in = a.plz_norm AND u.street_in = a.street_norm
        WHERE a.house_norm REGEXP '^[0-9]'
          AND TRY_CAST(REGEXP_EXTRACT(u.house_in,  '[0-9]+', 0) AS INTEGER) IS NOT NULL
          AND TRY_CAST(REGEXP_EXTRACT(a.house_norm, '[0-9]+', 0) AS INTEGER) IS NOT NULL
      )
      SELECT * FROM candidates WHERE rn = 1
    `);
  } catch (fuzzyErr) {
    // Fuzzy fallback failed — surface a visible warning so this is not hidden
    console.error("[Fix A] Fuzzy nearest-house query failed:", fuzzyErr);
    const warn = document.createElement("div");
    warn.id = "fuzzy-error-banner";
    warn.style.cssText =
      "background:#fff3cd; border:1px solid #ffc107; border-radius:6px; " +
      "padding:10px 14px; margin-bottom:12px; font-size:0.92em; color:#664d03;";
    warn.innerHTML =
      "<strong>⚠ Fix A (fuzzy nearest-house) failed</strong> — " +
      "some addresses may show as <em>unmatched</em> that could have been " +
      "recovered. Error: <code>" + fuzzyErr.message + "</code>. " +
      "Check the browser console for details.";
    const res = document.getElementById("results-section");
    if (res) res.prepend(warn);
    return exactResults;
  }

  if (!fuzzy) return exactResults;

  // Index fuzzy results by row_id
  const fuzzyMap = {};
  fuzzy.toArray().forEach(r => {
    // Fix D: convert acd_list Vector → plain JS array
    let acdArr = [];
    try {
      const raw = r.acd_list;
      if (raw != null) {
        if (typeof raw.toArray === "function") acdArr = raw.toArray().map(String);
        else if (Array.isArray(raw))           acdArr = raw.map(String);
        else                                   acdArr = [String(raw)];
      }
    } catch (_) { /* leave empty */ }

    fuzzyMap[Number(r.row_id)] = {
      ACD:            r.ACD,
      SCD:            r.SCD,
      STRABS:         r.STRABS,
      OBJEKT_ID:      r.OBJEKT_ID,
      lon:            r.lon,
      lat:            r.lat,
      house_distance: Number(r.house_distance),
      acd_list:       acdArr,
      acd_count:      r.acd_count != null ? Number(r.acd_count) : null
    };
  });

  // Patch the exactResults in-place: upgrade unmatched → fuzzy_nearest_house
  // only when the nearest house is within FUZZY_MAX_DISTANCE.
  return exactResults.map(r => {
    if (r.match_quality !== "unmatched" || r.composite_total !== 1) return r;
    const f = fuzzyMap[r.row_id];
    if (!f) return r;
    if (f.house_distance > FUZZY_MAX_DISTANCE) return r;
    return Object.assign({}, r, {
      ACD:            f.ACD,
      SCD:            f.SCD,
      STRABS:         f.STRABS,
      OBJEKT_ID:      f.OBJEKT_ID,
      lon:            f.lon,
      lat:            f.lat,
      house_distance: f.house_distance,
      acd_list:       f.acd_list,
      acd_count:      f.acd_count,
      match_quality:  "fuzzy_nearest_house"
    });
  });
}

// ── Combined lookup (exact + fuzzy) ───────────────────────────────────────
async function runLookup(expanded) {
  const exactResults = await runExactLookup(expanded);
  setProgress(80, "Fuzzy fallback pass…");
  return runFuzzyFallback(exactResults);
}

// ── Fix C — REST API fallback ──────────────────────────────────────────────
// Chunks an array into sub-arrays of at most `size` elements.
function chunks(arr, size) {
  const out = [];
  for (let i = 0; i < arr.length; i += size) out.push(arr.slice(i, i + size));
  return out;
}

// Session-level call budget (resets on page reload).
let restCallsUsed = 0;

async function restFallback(unmatchedRows, opts = {}) {
  const concurrency = opts.concurrency || 8;
  const maxCalls    = opts.maxCalls    || 250;
  const timeout     = opts.timeout     || 5000;
  const baseUrl     = "https://data.wien.gv.at/daten/OGDAddressService.svc/GetAddressInfo";

  const callsToMake = unmatchedRows.slice(0, maxCalls);
  const results     = [];
  const batches     = chunks(callsToMake, concurrency);
  let   done        = 0;

  for (const batch of batches) {
    const settled = await Promise.allSettled(batch.map(row => {
      const addr  = `${row.Strasse || row.__street__ || ""} ${row.HausNr || row.__house__ || ""}`.trim();
      const url   = `${baseUrl}?Address=${encodeURIComponent(addr)}&CRS=EPSG:4326`;
      const ctrl  = new AbortController();
      const timer = setTimeout(() => ctrl.abort(), timeout);
      return fetch(url, { signal: ctrl.signal })
        .then(r => {
          if (!r.ok) throw new Error(`HTTP ${r.status}`);
          return r.json();
        })
        .finally(() => clearTimeout(timer));
    }));

    settled.forEach((res, i) => {
      const row = batch[i];
      const f   = res.status === "fulfilled" && res.value?.features?.[0];
      if (f?.properties?.ACD) {
        results.push(Object.assign({}, row, {
          ACD:            f.properties.ACD,
          SCD:            f.properties.SCD       ?? "",
          STRABS:         f.properties.STRABS    ?? "",
          AdressID:       f.properties.AdressID  ?? "",
          lon:            f.geometry?.coordinates?.[0] ?? "",
          lat:            f.geometry?.coordinates?.[1] ?? "",
          match_quality:  "rest_api_fallback",
          rest_ranking:   f.properties.Ranking   ?? ""
        }));
      } else {
        results.push(Object.assign({}, row, { match_quality: "unmatched_after_rest" }));
      }
    });

    done += batch.length;
    restCallsUsed += batch.length;

    // Update progress UI
    const pct = Math.round(100 * done / callsToMake.length);
    const restMsg  = document.getElementById("rest-progress-msg");
    const restBar  = document.getElementById("rest-progress-bar");
    const restBudg = document.getElementById("rest-budget-display");
    if (restMsg)  restMsg.textContent  = `${done} / ${callsToMake.length} calls done…`;
    if (restBar)  restBar.style.width  = pct + "%";
    if (restBudg) restBudg.textContent =
      `${restCallsUsed} of ${maxCalls} max calls used this session`;
  }

  // Mark over-budget rows
  for (let i = maxCalls; i < unmatchedRows.length; i++) {
    results.push(Object.assign({}, unmatchedRows[i], { match_quality: "rest_skipped_over_budget" }));
  }

  return results;
}

// ── Merge results back to original rows ───────────────────────────────────
// Quality rank (lower = better):  exact=0, ambiguous_multi=1, fuzzy=2,
// split_both=3, split_partial=4, rest_api_fallback=5, unmatched_after_rest=97,
// rest_skipped_over_budget=98, unmatched=99
// Fix D: ambiguous_multi ranks just below exact — it IS a match, it's just
// a multi-unit building where we surface all ACDs instead of picking one.
const QUALITY_RANK = {
  exact:                     0,
  ambiguous_multi:           1,
  fuzzy_nearest_house:       2,
  split_both:                3,
  split_partial:             4,
  rest_api_fallback:         5,
  unmatched_after_rest:      97,
  rest_skipped_over_budget:  98,
  unmatched:                 99
};
function qualityRank(q) { return QUALITY_RANK[q] ?? 98; }

function mergeResults(origRows, expanded, joinedRows) {
  // Group expanded results by orig_idx
  const byOrig = {};
  joinedRows.forEach(r => {
    const k = r.orig_idx;
    if (!byOrig[k]) byOrig[k] = [];
    byOrig[k].push(r);
  });

  return origRows.map((row, idx) => {
    const parts = byOrig[idx] || [];
    if (parts.length === 0) {
      return Object.assign({}, row, {
        ACD: "", SCD: "", STRABS: "", OBJEKT_ID: "", lon: "", lat: "",
        house_distance: "", acd_b: "",
        acd_count: "", acd_codes: "",
        match_quality: "unmatched"
      });
    }

    const compositeTotal = parts[0].composite_total;

    if (compositeTotal <= 1) {
      // Non-composite: just pick the best (should be one row)
      const best = parts.reduce((a, b) =>
        qualityRank(a.match_quality) <= qualityRank(b.match_quality) ? a : b
      );
      // Fix D: surface acd_count and acd_codes from the grouped view result
      const cnt   = best.acd_count ?? (best.ACD ? 1 : 0);
      const codes = (Array.isArray(best.acd_list) && best.acd_list.length > 0)
        ? best.acd_list.join(",")
        : (best.ACD ?? "");
      return Object.assign({}, row, {
        ACD:            best.ACD           ?? "",
        SCD:            best.SCD           ?? "",
        STRABS:         best.STRABS        ?? "",
        OBJEKT_ID:      best.OBJEKT_ID     ?? "",
        lon:            best.lon           ?? "",
        lat:            best.lat           ?? "",
        house_distance: best.house_distance ?? "",
        acd_b:          "",
        acd_count:      cnt,
        acd_codes:      codes,
        match_quality:  best.match_quality ?? "unmatched"
      });
    }

    // Composite row: parts[0] = first half, parts[1] = second half (if present)
    const p0 = parts.find(p => p.composite_index === 0);
    const p1 = parts.find(p => p.composite_index === 1);
    const m0 = p0 && p0.ACD ? true : false;
    const m1 = p1 && p1.ACD ? true : false;

    let matchQuality;
    if (m0 && m1)       matchQuality = "split_both";
    else if (m0 || m1)  matchQuality = "split_partial";
    else                matchQuality = "unmatched";

    const primary = m0 ? p0 : (m1 ? p1 : p0 || {});
    return Object.assign({}, row, {
      ACD:            primary.ACD           ?? "",
      SCD:            primary.SCD           ?? "",
      STRABS:         primary.STRABS        ?? "",
      OBJEKT_ID:      primary.OBJEKT_ID     ?? "",
      lon:            primary.lon           ?? "",
      lat:            primary.lat           ?? "",
      house_distance: "",
      acd_b:          (m1 && p1 ? p1.ACD : "") ?? "",
      acd_count:      primary.acd_count ?? 1,
      acd_codes:      (Array.isArray(primary.acd_list) && primary.acd_list.length > 0)
                        ? primary.acd_list.join(",")
                        : (primary.ACD ?? ""),
      match_quality:  matchQuality
    });
  });
}

// ── Match-rate chart ───────────────────────────────────────────────────────
function renderChart(merged) {
  const byDistrict = {};
  merged.forEach(r => {
    const plz = r[Object.keys(r).find(k => k === "PLZ" || k === "_plz_")] ??
                r.__plzCol__ ?? r._plzVal_ ?? "";
    // Use plz_in if available (we stored it separately)
    const key = r.__plz__ || "";
    if (!byDistrict[key]) byDistrict[key] = { total: 0, matched: 0 };
    byDistrict[key].total++;
    if (r.match_quality !== "unmatched") byDistrict[key].matched++;
  });
  // Build sorted array: descending by match rate
  const districtData = Object.entries(byDistrict).map(([key, val]) => ({
    district: key,
    total:    val.total,
    matched:  val.matched,
    rate:     val.total > 0 ? Math.round(100 * val.matched / val.total) : 0
  })).sort((a, b) => b.rate - a.rate);

  const canvas = document.getElementById("district-chart");
  const existing = Chart.getChart(canvas);
  if (existing) existing.destroy();

  // Cleveland dot plot: type="scatter", x=rate, y=integer index
  const points = districtData.map((d, i) => ({ x: d.rate, y: i }));

  new Chart(canvas, {
    type: "scatter",
    data: {
      datasets: [{
        data: points,
        pointRadius: 6,
        pointBackgroundColor: "#5dadff",   // 4.5:1 contrast on #1a1a1a
        pointBorderColor: "#ffffff",
        pointBorderWidth: 1.5
      }]
    },
    options: {
      responsive: true,
      plugins: {
        legend: { display: false },
        tooltip: {
          callbacks: {
            label: ctx => {
              const d = districtData[ctx.parsed.y];
              return d ? `${d.district}: ${d.rate}%` : ctx.parsed.x + "%";
            }
          }
        }
      },
      scales: {
        x: {
          min: 0, max: 100,
          title: { display: true, text: "Match rate (%)", color: "#ffffff" },
          ticks: { color: "#ffffff", callback: v => v + "%" },
          grid:  { color: "rgba(255,255,255,0.15)" }
        },
        y: {
          type: "linear",
          min: -0.5,
          max: districtData.length - 0.5,
          reverse: false,
          ticks: {
            color: "#ffffff",
            stepSize: 1,
            callback: (val) => {
              const d = districtData[val];
              return d ? d.district : "";
            }
          },
          grid: { color: "rgba(255,255,255,0.15)" }
        }
      }
    }
  });

  // ── Dynamic 7-item bilingual caption ────────────────────────────────────
  const nAbove90 = districtData.filter(d => d.rate >= 90).length;
  const top = districtData[0] || { district: "–", rate: 0 };
  const bot = districtData[districtData.length - 1] || { district: "–", rate: 0 };
  const lang = document.documentElement.lang || "en";
  const isDE = lang.startsWith("de");

  const captionEN = `Cleveland dot plot of address-to-ACD match rate by Vienna district (Bezirk). ` +
    `x\u202f=\u202fmatch rate (%, range 0\u2013100); y\u202f=\u202fdistrict postal code (PLZ). ` +
    `Each blue dot represents one district; districts sorted by match rate descending. ` +
    `Highest: ${top.district} at ${top.rate}%; lowest: ${bot.district} at ${bot.rate}%; ` +
    `${nAbove90} of ${districtData.length} districts achieved \u226590%. ` +
    `Source: user-uploaded XLSX joined to ADRESSENOGD Parquet via DuckDB-WASM. ` +
    `See <a href="#how-it-works" style="color:#5dadff;">methodology tabs below</a> for the per-fix breakdown. ` +
    `ACD\u202f=\u202faddress-cluster designator; Bezirk\u202f=\u202fVienna municipal district.`;

  const captionDE = `Cleveland-Punktdiagramm der Adress-zu-ACD-Trefferquote nach Wiener Bezirk. ` +
    `x\u202f=\u202fTrefferquote (%, Bereich 0\u2013100); y\u202f=\u202fBezirk (PLZ). ` +
    `Jeder blaue Punkt steht f\u00fcr einen Bezirk; Bezirke absteigend nach Trefferquote sortiert. ` +
    `H\u00f6chster: ${top.district} mit ${top.rate}%; niedrigster: ${bot.district} mit ${bot.rate}%; ` +
    `${nAbove90} von ${districtData.length} Bezirken erreichten \u226590%. ` +
    `Quelle: Benutzer-XLSX verkn\u00fcpft mit ADRESSENOGD-Parquet via DuckDB-WASM. ` +
    `Siehe <a href="#how-it-works" style="color:#5dadff;">Methodik-Tabs unten</a> f\u00fcr die Einzelaufschl\u00fcsselung. ` +
    `ACD\u202f=\u202fAdress-Cluster-Bezeichner; Bezirk\u202f=\u202fWiener Stadtbezirk.`;

  const captionEl = document.getElementById("district-chart-caption");
  if (captionEl) captionEl.innerHTML = isDE ? captionDE : captionEN;

  // ── Accessible data table ───────────────────────────────────────────────
  const tbody = document.getElementById("district-data-tbody");
  if (tbody) {
    tbody.innerHTML = districtData.map(d =>
      `<tr>
        <td style="border:1px solid #555; padding:2px 8px;">${d.district}</td>
        <td style="border:1px solid #555; padding:2px 8px; text-align:right;">${d.total}</td>
        <td style="border:1px solid #555; padding:2px 8px; text-align:right;">${d.matched}</td>
        <td style="border:1px solid #555; padding:2px 8px; text-align:right;">${d.rate}</td>
      </tr>`
    ).join("");
  }
}

// ── HTML table (first 50 rows) ─────────────────────────────────────────────
function renderTable(merged) {
  const tbl  = document.getElementById("results-table");
  // Fix D: exclude the raw acd_list array from the display table (it's an
  // internal object); acd_count and acd_codes are shown instead.
  const cols = Object.keys(merged[0] || {}).filter(
    c => !c.startsWith("__") && c !== "acd_list"
  );
  const rows = merged.slice(0, 50);

  const head = `<thead><tr>${cols.map(c =>
    `<th style="border:1px solid #dee2e6; padding:4px 8px; background:#f8f9fa; white-space:nowrap;">${c}</th>`
  ).join("")}</tr></thead>`;

  const body = `<tbody>${rows.map(r =>
    `<tr>${cols.map(c => {
      const v   = r[c] ?? "";
      const isQ = c === "match_quality";
      const isA = c === "ACD";  // Fix D: badge next to ACD cell when ambiguous
      const style = isQ && v === "exact"                     ? "background:#d1e7dd;" :
                    isQ && v === "ambiguous_multi"           ? "background:#e9d8fd;" :
                    isQ && v === "fuzzy_nearest_house"       ? "background:#fff3cd;" :
                    isQ && v === "split_both"                ? "background:#cff4fc;" :
                    isQ && v === "split_partial"             ? "background:#e2e3e5;" :
                    isQ && v === "rest_api_fallback"         ? "background:#ffd9b3;" :
                    isQ && v === "unmatched_after_rest"      ? "background:#f8d7da;" :
                    isQ && v === "rest_skipped_over_budget"  ? "background:#f0f0f0;" :
                    isQ && v === "unmatched"                 ? "background:#f8d7da;" : "";
      // Fix D: for the ACD column, append a badge and expandable code list
      // when this row has acd_count > 1.
      if (isA && r.match_quality === "ambiguous_multi" && r.acd_count > 1) {
        const cnt   = r.acd_count;
        const codes = r.acd_codes || String(v);
        const uid   = `acd-expand-${Math.random().toString(36).slice(2)}`;
        return `<td style="border:1px solid #dee2e6; padding:4px 8px; background:#f3e8ff;">` +
          `${v} ` +
          `<span title="Multi-unit building: ${cnt} ACDs match this address. Click to see all."` +
               ` style="cursor:pointer; color:#6f42c1; font-weight:600; white-space:nowrap;"` +
               ` onclick="document.getElementById('${uid}').style.display=` +
                  `document.getElementById('${uid}').style.display==='none'?'block':'none'">` +
            `&#9888; ${cnt} units` +
          `</span>` +
          `<div id="${uid}" style="display:none; margin-top:4px; font-size:0.8em; color:#6f42c1; word-break:break-all;">` +
            codes +
          `</div>` +
          `</td>`;
      }
      return `<td style="border:1px solid #dee2e6; padding:4px 8px; ${style}">${v}</td>`;
    }).join("")}</tr>`
  ).join("")}</tbody>`;

  tbl.innerHTML = head + body;
}

// ── CSV download ───────────────────────────────────────────────────────────
// Fix D: mode = "first" (default, 1:1 with input) or "all" (one row per ACD
// for ambiguous_multi rows, with an acd_unit_index column for joining back).
function csvEsc(v) {
  const s = String(v ?? "");
  return s.includes(",") || s.includes('"') || s.includes("\n")
    ? `"${s.replace(/"/g, '""')}"` : s;
}

function buildCsvRows(merged, mode) {
  // Columns to emit — exclude internal-only fields
  const allCols = Object.keys(merged[0] || {}).filter(
    c => !c.startsWith("__") && c !== "acd_list"
  );

  if (mode !== "all") {
    // "First ACD only" — one row per input row (backwards compatible)
    return { cols: allCols, rows: merged };
  }

  // "All ACDs" — expand ambiguous_multi rows
  const expandedCols = [...allCols, "acd_unit_index"];
  const expandedRows = [];
  merged.forEach(r => {
    if (r.match_quality === "ambiguous_multi" &&
        Array.isArray(r.acd_list) && r.acd_list.length > 1) {
      r.acd_list.forEach((acd, i) => {
        expandedRows.push(Object.assign({}, r, {
          ACD:            acd,
          acd_unit_index: i
        }));
      });
    } else {
      expandedRows.push(Object.assign({}, r, { acd_unit_index: 0 }));
    }
  });
  return { cols: expandedCols, rows: expandedRows };
}

function downloadCsv(merged) {
  const modeEl = document.querySelector('input[name="csv-mode"]:checked');
  const mode   = modeEl ? modeEl.value : "first";
  const { cols, rows } = buildCsvRows(merged, mode);

  const header = cols.join(",");
  const body   = rows.map(r => cols.map(c => csvEsc(r[c])).join(",")).join("\n");
  const csv    = header + "\n" + body;
  const blob   = new Blob([csv], { type: "text/csv" });
  const url    = URL.createObjectURL(blob);
  const a      = document.createElement("a");
  a.href       = url;
  a.download   = mode === "all" ? "addresses_with_acd_all_units.csv" : "addresses_with_acd.csv";
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 5000);
}

// ── File parsing ───────────────────────────────────────────────────────────
function autoDetect(cols) {
  const norm = c => c.toLowerCase().replace(/[^a-z]/g, "");
  const find = (keys) => cols.find(c => keys.includes(norm(c))) ?? cols[0];
  return {
    plz:    find(["plz", "postcode", "zip", "postleitzahl"]),
    street: find(["strasse", "street", "strase", "str", "streetname", "strassename", "name"]),
    house:  find(["hausnr", "hnr", "hausnummer", "nr", "housenumber", "number"])
  };
}

function populateSelects(cols, detected) {
  ["map-plz", "map-street", "map-hausnr"].forEach(id => {
    const sel = document.getElementById(id);
    sel.innerHTML = cols.map(c =>
      `<option value="${c}">${c}</option>`
    ).join("");
  });
  document.getElementById("map-plz").value    = detected.plz;
  document.getElementById("map-street").value = detected.street;
  document.getElementById("map-hausnr").value = detected.house;
}

async function parseFile(file) {
  const ext = file.name.split(".").pop().toLowerCase();
  if (ext === "csv") {
    return new Promise(resolve => {
      Papa.parse(file, {
        header: true,
        skipEmptyLines: true,
        complete: r => resolve({ rows: r.data, cols: r.meta.fields })
      });
    });
  } else {
    // xlsx
    const ab   = await file.arrayBuffer();
    const wb   = XLSX.read(ab, { type: "array" });
    const ws   = wb.Sheets[wb.SheetNames[0]];
    const rows = XLSX.utils.sheet_to_json(ws, { defval: "" });
    const cols = rows.length > 0 ? Object.keys(rows[0]) : [];
    return { rows, cols };
  }
}

// ── Match summary helper (used by both main run and REST update) ───────────
function updateMatchSummary(merged) {
  const nTotal          = merged.length;
  const nExact          = merged.filter(r => r.match_quality === "exact").length;
  const nAmbiguous      = merged.filter(r => r.match_quality === "ambiguous_multi").length;  // Fix D
  const nFuzzy          = merged.filter(r => r.match_quality === "fuzzy_nearest_house").length;
  const nSplitBoth      = merged.filter(r => r.match_quality === "split_both").length;
  const nSplitPartial   = merged.filter(r => r.match_quality === "split_partial").length;
  const nRestApi        = merged.filter(r => r.match_quality === "rest_api_fallback").length;
  const nAnyMatch       = nExact + nAmbiguous + nFuzzy + nSplitBoth + nSplitPartial + nRestApi;
  const nUnmatched      = nTotal - nAnyMatch;
  const pct             = nTotal > 0 ? Math.round(100 * nAnyMatch / nTotal) : 0;

  const lang = document.body.getAttribute("lang") || "en";
  const isDE = lang === "de";
  document.getElementById("match-summary").innerHTML =
    `<strong>${nAnyMatch.toLocaleString()}</strong> ` +
    (isDE ? "von" : "of") +
    ` <strong>${nTotal.toLocaleString()}</strong> ` +
    (isDE ? "Adressen zugeordnet" : "addresses matched") +
    ` (${pct}%). ` +
    `<span style="color:#198754;">&#10003; exact: ${nExact.toLocaleString()}</span>` +
    // Fix D: ambiguous_multi shown inline with count
    (nAmbiguous    > 0 ? ` &nbsp; <span style="color:#6f42c1; font-weight:600;">&#9888; ambiguous (multi-unit): ${nAmbiguous.toLocaleString()}</span>` : "") +
    (nFuzzy        > 0 ? ` &nbsp; <span style="color:#fd7e14;">~ fuzzy: ${nFuzzy.toLocaleString()}</span>` : "") +
    (nSplitBoth    > 0 ? ` &nbsp; <span style="color:#0dcaf0;">&#8679; split (both): ${nSplitBoth.toLocaleString()}</span>` : "") +
    (nSplitPartial > 0 ? ` &nbsp; <span style="color:#6c757d;">&#8679; split (partial): ${nSplitPartial.toLocaleString()}</span>` : "") +
    (nRestApi      > 0 ? ` &nbsp; <span style="color:#fd7e14; font-weight:600;">&#127760; REST API: ${nRestApi.toLocaleString()}</span>` : "") +
    ` &nbsp; <span style="color:#dc3545;">&#10007; ` +
    (isDE ? "keine Übereinstimmung" : "unmatched") +
    `: ${nUnmatched.toLocaleString()}</span>`;
}

// ── Wire up UI ─────────────────────────────────────────────────────────────
document.getElementById("drop-zone").addEventListener("click", () =>
  document.getElementById("file-input").click()
);

document.getElementById("drop-zone").addEventListener("dragover", e => {
  e.preventDefault();
  document.getElementById("drop-zone").style.background = "#e9ecef";
});

document.getElementById("drop-zone").addEventListener("dragleave", () => {
  document.getElementById("drop-zone").style.background = "#f8f9fa";
});

document.getElementById("drop-zone").addEventListener("drop", async e => {
  e.preventDefault();
  document.getElementById("drop-zone").style.background = "#f8f9fa";
  const file = e.dataTransfer.files[0];
  if (file) await handleFile(file);
});

document.getElementById("file-input").addEventListener("change", async e => {
  const file = e.target.files[0];
  if (file) await handleFile(file);
});

// "Try with sample" button: fetch the bundled xlsx and run it through the
// same handleFile() pipeline as a real upload would.
document.getElementById("try-sample-btn").addEventListener("click", async () => {
  setProgress(5, "Fetching sample file…");
  try {
    const resp = await fetch("../../data/sample_acd_test.xlsx");
    if (!resp.ok) throw new Error(`HTTP ${resp.status}`);
    const blob = await resp.blob();
    const file = new File([blob], "sample_acd_test.xlsx",
      { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" });
    await handleFile(file);
  } catch (err) {
    setProgress(0, "Could not load sample: " + err.message);
  }
});

async function handleFile(file) {
  document.getElementById("file-name-display").textContent = file.name;
  document.getElementById("empty-state-msg").style.display = "none";
  setProgress(5, "Parsing file…");

  try {
    const { rows, cols } = await parseFile(file);
    parsedRows  = rows;
    colHeaders  = cols;
    const det   = autoDetect(cols);
    populateSelects(cols, det);
    document.getElementById("col-map-section").style.display = "block";
    // Enable run button now that a file is loaded
    const runBtn = document.getElementById("run-btn");
    runBtn.disabled       = false;
    runBtn.style.cursor   = "pointer";
    runBtn.style.opacity  = "1";
    setProgress(100, "");
  } catch (err) {
    setProgress(100, "");
    alert("Could not parse file: " + err.message);
  }
}

document.getElementById("run-btn").addEventListener("click", async () => {
  const plzCol    = document.getElementById("map-plz").value;
  const streetCol = document.getElementById("map-street").value;
  const houseCol  = document.getElementById("map-hausnr").value;

  document.getElementById("empty-state-msg").style.display = "none";
  document.getElementById("results-section").style.display = "none";

  try {
    await initDuck();

    setProgress(40, "Expanding rows (composite split + garden-plot detection)…");
    // Fix B: splitComposite replaces the old expandRows — handles "/" splits correctly
    const expanded = splitComposite(parsedRows, plzCol, streetCol, houseCol);

    // Fix A: runLookup now does exact pass + fuzzy fallback
    const joinedRows = await runLookup(expanded);

    // Tag each orig row with its PLZ for chart
    const withPlz = parsedRows.map((r, idx) => ({
      ...r,
      __plz__: String(r[plzCol] ?? "").trim()
    }));

    const merged = mergeResults(withPlz, expanded, joinedRows);

    resultRows = merged;

    const nTotal         = merged.length;
    const nExact         = merged.filter(r => r.match_quality === "exact").length;
    const nAmbiguous     = merged.filter(r => r.match_quality === "ambiguous_multi").length;  // Fix D
    const nFuzzy         = merged.filter(r => r.match_quality === "fuzzy_nearest_house").length;
    const nSplitBoth     = merged.filter(r => r.match_quality === "split_both").length;
    const nSplitPartial  = merged.filter(r => r.match_quality === "split_partial").length;
    const nAnyMatch      = nExact + nAmbiguous + nFuzzy + nSplitBoth + nSplitPartial;
    const nUnmatched     = nTotal - nAnyMatch;
    const pct            = nTotal > 0 ? Math.round(100 * nAnyMatch / nTotal) : 0;

    updateMatchSummary(merged);

    renderChart(merged);
    renderTable(merged);

    document.getElementById("results-section").style.display = "block";
    setProgress(100, "");

    // Fix D: show CSV mode toggle if any ambiguous_multi rows exist
    const csvToggle = document.getElementById("csv-mode-toggle");
    if (csvToggle) csvToggle.style.display = nAmbiguous > 0 ? "block" : "none";

    // Show REST fallback button if there are unmatched rows
    const restSec = document.getElementById("rest-fallback-section");
    if (nUnmatched > 0) {
      const el1 = document.getElementById("rest-unmatched-count");
      const el2 = document.getElementById("rest-unmatched-count-de");
      if (el1) el1.textContent = nUnmatched.toLocaleString();
      if (el2) el2.textContent = nUnmatched.toLocaleString();
      const restBudg = document.getElementById("rest-budget-display");
      if (restBudg) restBudg.textContent =
        `${restCallsUsed} of 250 max calls used this session`;
      restSec.style.display = "block";
    } else {
      restSec.style.display = "none";
    }
  } catch (err) {
    setProgress(100, "");
    console.error(err);
    alert("Lookup failed: " + err.message +
          "\n\nCheck the browser console for details.");
  }
});

document.getElementById("download-btn").addEventListener("click", () => {
  if (resultRows.length > 0) downloadCsv(resultRows);
});

// ── Fix C — REST API fallback button ──────────────────────────────────────
document.getElementById("rest-btn").addEventListener("click", async () => {
  const btn = document.getElementById("rest-btn");
  btn.disabled = true;

  const lang = document.body.getAttribute("lang") || "en";
  const isDE = lang === "de";

  // Identify rows still unmatched (only true 'unmatched' rows; skip composites)
  // We need to supply street/house from the original columns.
  // resultRows carry the original user columns plus ACD/match_quality additions.
  const plzCol    = document.getElementById("map-plz").value;
  const streetCol = document.getElementById("map-street").value;
  const houseCol  = document.getElementById("map-hausnr").value;

  const unmatched = resultRows.filter(r =>
    r.match_quality === "unmatched"
  ).map(r => Object.assign({}, r, {
    // Provide normalised aliases the restFallback function can read
    Strasse: String(r[streetCol] ?? "").trim(),
    HausNr:  String(r[houseCol]  ?? "").trim()
  }));

  if (unmatched.length === 0) {
    btn.disabled = false;
    return;
  }

  const progressWrap = document.getElementById("rest-progress-wrap");
  const restBar      = document.getElementById("rest-progress-bar");
  const restMsg      = document.getElementById("rest-progress-msg");
  progressWrap.style.display = "block";
  restBar.style.width        = "0%";
  restMsg.textContent        =
    isDE ? "REST API wird aufgerufen…" : "Calling REST API…";

  try {
    const apiResults = await restFallback(unmatched, {
      concurrency: 8,
      maxCalls:    250,
      timeout:     5000
    });

    // Merge apiResults back into resultRows by object identity (ref comparison
    // won't work after map), so use a positional index map via a WeakMap.
    // Strategy: apiResults items carry the same PLZ/street/house keys; build
    // a lookup keyed by the row's position in the unmatched list and splice
    // back using the row index stored in __restIdx__.
    const apiByIdx = {};
    apiResults.forEach((r, i) => { apiByIdx[i] = r; });

    // Rebuild resultRows: replace unmatched rows with their API results
    let apiCursor = 0;
    resultRows = resultRows.map(r => {
      if (r.match_quality !== "unmatched") return r;
      const updated = apiByIdx[apiCursor++];
      return updated ?? r;
    });

    updateMatchSummary(resultRows);
    renderChart(resultRows);
    renderTable(resultRows);

    // Update or hide the REST section
    const nStillUnmatched = resultRows.filter(
      r => r.match_quality === "unmatched" ||
           r.match_quality === "unmatched_after_rest"
    ).length;
    const el1 = document.getElementById("rest-unmatched-count");
    const el2 = document.getElementById("rest-unmatched-count-de");
    if (el1) el1.textContent = nStillUnmatched.toLocaleString();
    if (el2) el2.textContent = nStillUnmatched.toLocaleString();

    const restBudg = document.getElementById("rest-budget-display");
    if (restBudg) restBudg.textContent =
      `${restCallsUsed} of 250 max calls used this session`;

    restMsg.textContent = isDE
      ? `Fertig — ${apiResults.filter(r => r.match_quality === "rest_api_fallback").length} zusätzliche Treffer via REST API`
      : `Done — ${apiResults.filter(r => r.match_quality === "rest_api_fallback").length} additional matches via REST API`;

    progressWrap.style.display = "block";
    // Disable button to avoid double-calling
    btn.textContent = isDE ? "✓ REST API abgeschlossen" : "✓ REST API done";

  } catch (err) {
    restMsg.textContent = (isDE ? "Fehler: " : "Error: ") + err.message;
    btn.disabled = false;
  }
});
</script>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>